#!/usr/bin/env python3
"""Pass 4: Cover remaining ~1068 untranslated keys."""
import json, re, copy

SRC = "frontend/messages/en.json"
DST = "frontend/messages/ar.json"

def load_json_no_dup(path):
    with open(path, encoding="utf-8") as f:
        return json.load(f, object_pairs_hook=lambda pairs: dict(pairs))

en = load_json_no_dup(SRC)
ar = load_json_no_dup(DST)

# ── Direct-key overrides (key → Arabic) ─────────────────────────────────────
DIRECT = {
    # Acronyms / short identifiers
    "eta": "تاريخ الاستحقاق المتوقع",
    "urn": "URN",
    "undefined": "--",
    "sso": "SSO",
    "pmbok": "PMBOK",
    "iam": "إدارة الهوية والوصول",
    "crq": "تحديد الخطر الكمي",
    "notSet": "--",
    "p1": "P1",
    "p2": "P2",
    "p3": "P3",
    "p4": "P4",
    "iso27005": "ISO 27005",
    "gdpr": "اللائحة العامة لحماية البيانات",
    "tprm": "إدارة مخاطر الطرف الثالث",
    "core": "الأساسي",
    "cal": "التقويم",
    "jira": "Jira",
    "itsm": "إدارة خدمات تقنية المعلومات",
    "serviceNow": "ServiceNow",
    "servicenow": "ServiceNow",

    # Operating modes
    "operatingModesDescription": "ملخص أوضاع التشغيل",
    "operatingModes": "أوضاع التشغيل",
    "operatingMode": "وضع التشغيل",
    "associatedOperatingModes": "أوضاع التشغيل المرتبطة",
    "addOperatingMode": "إضافة وضع تشغيل",
    "returnToMo": "العودة إلى وضع التشغيل",
    "moGraph": "الرسم البياني",

    # EBIOS RM tooltips
    "ebiosWs2_2_tooltip": "تحتاج إلى زوج RO/TO واحد على الأقل لتقييمه",
    "ebiosWs2_3_tooltip": "تحتاج إلى زوج RO/TO واحد على الأقل لاختياره",
    "ebiosWs3_2_tooltip": "تحتاج إلى زوج RO/TO محدد واحد على الأقل لوضع سيناريو استراتيجي",
    "ebiosWs3_3_tooltip": "تحتاج إلى صاحب مصلحة واحد على الأقل لتحديد تدابير الأمان المرتبطة",
    "ebiosWs4_2_tooltip": "تحتاج إلى مسار هجوم واحد على الأقل محدد من سيناريو استراتيجي لوضع سيناريو تشغيلي",
    "ebiosWs4_3_tooltip": "تحتاج إلى سيناريو تشغيلي واحد على الأقل لتقييم احتماليته",
    "ebiosWs5_tooltip": "لم يتم إجراء أي تقييم للمخاطر بعد",
    "activityHelpText": "ما مستوى نشاط منشأ الخطر في نطاق الدراسة؟",
    "ebiosRadarParameters": "معلمات رادار EBIOS RM",
    "maxRadius": "الحد الأقصى للنصف القطري",
    "greenZoneRadius": "نصف قطر المنطقة الخضراء",
    "yellowZoneRadius": "نصف قطر المنطقة الصفراء",
    "redZoneRadius": "نصف قطر المنطقة الحمراء",
    "ebiosReconnaissance": "الاستطلاع",
    "ebiosInitialAccess": "الوصول الأولي",
    "ebiosDiscovery": "الاستكشاف",
    "ebiosExploitation": "الاستغلال",
    "ebiosOperationalScenarioHelp": "تُقدّم مسارات الهجوم وصفاً رفيع المستوى لكيفية تكشّف سيناريو استراتيجي (من ورشة العمل 3). وبينما قد يضم السيناريو الاستراتيجي مسارات هجوم متعددة، يُترجَم كل مسار إلى سيناريو تشغيلي واحد في ورشة العمل 4.",
    "ebiosRmDefaults": "تقييم الحرجية السريع (EBIOS RM)",
    "ebiosRmDefaultsHelpText": "القيم الافتراضية للتبعية والنفاذية والنضج والثقة عند إنشاء أصحاب المصلحة في ورشة العمل 3 من EBIOS RM",
    "ebiosRmSyncModalTitle": "خيارات تقييم المخاطر",
    "ebiosRmSyncModalBody": "يوجد تقييم مخاطر لهذه الدراسة بالفعل: \"{name}\"\n\nهل تريد:",
    "ebiosRmSyncExisting": "مزامنة الموجود",
    "ebiosRmCreateNew": "إنشاء جديد",
    "reminderWarningStrategicScenarios": "تذكير: لا تنس تحديد مسارات الهجوم لإجراء السيناريوهات التشغيلية",
    "addAttackPathToDoOperationalScenarios": "يجب إضافة مسار هجوم إلى هذه السيناريوهات الاستراتيجية إذا كنت تريد استخدامها في السيناريوهات التشغيلية:",

    # Graph/kill chain
    "graphAnimate": "تحريك",
    "graphMoHelp": "يمكنك تحريك عقد الرسم البياني لتحسين العرض وتقليل تقاطع الروابط.",
    "graphEditorHelp": "اسحب الإجراءات من الشريط الجانبي وصلها. تظهر عوامل المنطق (AND/OR) تلقائياً عند توجيه حواف متعددة نحو عقدة — انقر للتبديل. لإزالة اتصال، حدده واضغط Backspace.",
    "editGraph": "تعديل الرسم البياني",
    "viewGraph": "عرض الرسم البياني",
    "unsavedChanges": "تغييرات غير محفوظة",
    "discardChanges": "تجاهل",
    "logicAnd": "AND",
    "logicOr": "OR",
    "logicOperator": "عامل المنطق",
    "logicOperatorHelpText": "يمكن تجميع المسبقات (اثنان أو أكثر) باستخدام العمليات المنطقية.",
    "isHighlighted": "مميز",
    "killChainConsistencyError": "تغيير مرحلة الهجوم سيكسر تسلسل kill chain في أوضاع التشغيل التالية:",
    "killChains": "Kill chain",
    "killChain": "خطوة kill chain",
    "associatedKillChains": "خطوات kill chain",
    "killChainSteps": "خطوات kill chain",

    # Elementary actions
    "elementaryActions": "الإجراءات الأولية",
    "elementaryAction": "إجراء أولي",
    "associatedElementaryActions": "الإجراءات الأولية المرتبطة",
    "selectElementaryActions": "اختيار الإجراءات الأولية",

    # Attack stage / antecedents
    "attackStage": "مرحلة الهجوم",
    "antecedents": "المسبقات",
    "antecedentsHelpText": "المسبقات لا تنطبق على الإجراءات في مرحلة 'المعرفة' لأنها تمثل الخطوات الأولية لمسار الهجوم.",

    # Score results
    "documentationScoreResult": "نتيجة توثيق: ",
    "implementationScoreResult": "نتيجة التنفيذ: ",
    "percentageDisplay": "{number}٪",

    # Libraries
    "noEvidences": "لا توجد أدلة",
    "missingLibrariesInImport": "بعض المكتبات مفقودة أو غير محدّثة، انظر القائمة أعلاه",
    "loadMissingLibraries": "تحميل المكتبات المفقودة",
    "loadMissingLibrariesHelpText": "حمّل المكتبات المفقودة لإتمام الاستيراد إذا كانت متاحة.",
    "updateAvailable": "يتوفر تحديث",
    "libraryOverview": "{objectType}: {count}",

    # Guided tour / welcome
    "showGuidedTour": "جولة إرشادية",
    "showGuidedTourDescription": "استعرض الواجهة وتعرف على الميزات الرئيسية",
    "loadDemoData": "تحميل بيانات تجريبية",
    "loadDemoDataDescription": "استيراد بيئة نموذجية لاستكشاف المنصة",
    "importingDemoData": "جاري استيراد البيانات التجريبية...",
    "demoEnvironmentBeingPrepared": "قد يستغرق ذلك بضع ثوانٍ. جاري إعداد بيئتك التجريبية.",
    "firstTimeLoginModalTitle": "مرحباً بك في منصة SICO GRC!",
    "firstTimeLoginModalDescription": "اختر الطريقة التي تريد البدء بها. يمكنك دائماً تغيير الأشياء لاحقاً.",
    "browsePresetsDescription": "إعداد الأطر وتقييمات المخاطر ومسارات الامتثال تلقائياً",
    "customizeFeatureFlags": "تخصيص تجربتي",
    "skipForNow": "تخطي في الوقت الحالي",
    "demoDataAlreadyImported": "تم استيراد البيانات التجريبية بالفعل. احذف نطاق DEMO الموجود أو أعد تسميته.",
    "welcomeToCISOAssistant": "مرحباً بك في منصة SICO GRC",
    "noDomainsYet": "لم تنشئ أي نطاق بعد. ابدأ بنموذج لإعداد أطرك وتقييمات المخاطر ومسارات الامتثال تلقائياً.",
    "browsePresets": "استعراض المسارات",

    # Compliance analytics
    "complianceAnalytics": "التقدم حسب الإطار",
    "noComplianceData": "لا توجد بيانات",
    "sectionMoved": "القسم منقول هنا",
    "activityCalendar": "تقويم النشاط",
    "filterBy": "تصفية حسب",

    # Findings
    "findingsExplorer": "مراجعة النتائج المدمجة",
    "findingsAssessments": "المتابعات",
    "quantitativeRiskStudies": "دراسات CRQ",
    "quantitativeRiskScenarios": "سيناريوهات CRQ",
    "followUp": "تتبع النتائج",
    "pentest": "اختبار الاختراق",
    "selfIdentified": "محدد ذاتياً",
    "identified": "محدد",
    "confirmed": "مؤكد",
    "dismissed": "مرفوض",
    "assigned": "مسنَد",
    "selectEvidence": "اختيار دليل",

    # Compliance
    "compliantRequirementsSemiColon": "المتطلبات الممتثلة:",
    "requirementsProgressionSemiColon": "تقدم المتطلبات:",
    "noRequirementFound": "لم يُعثر على تقييم متطلب",
    "noAuditForTheFramework": "لا يوجد تدقيق يستخدم هذا الإطار",
    "AuditExistsYoullSeeOverallCompliance": "بمجرد وجود تدقيق، سترى هنا الامتثال الإجمالي والرسوم البيانية وخيارات التصدير.",

    # Question types
    "multipleChoice": "اختيار متعدد",
    "uniqueChoice": "اختيار منفرد",
    "text": "نص",
    "entry": "إدخال",

    # Operations analytics
    "operationsAnalytics": "تحليلات العمليات",
    "incidentDetectionBreakdown": "مصدر الكشف",
    "noOperationsData": "لا تتوفر بيانات عمليات",
    "noQualificationsData": "لم يُعثر على تصنيفات للحوادث",
    "totalIncidents": "إجمالي الحوادث",
    "incidentsThisMonth": "حوادث هذا الشهر",
    "openIncidents": "الحوادث المفتوحة",
    "findingsBreakdown": "توزيع النتائج",
    "noFindingsData": "لا تتوفر بيانات نتائج",
    "monthlyCount": "العدد الشهري",
    "cumulativeCount": "العدد التراكمي",
    "createAssessment": "إنشاء تقييم",
    "securityExceptionFlow": "توزيع الاستثناءات",
    "noExceptionData": "لم يُعثر على استثناءات أمنية",

    # Timeline
    "timestamp": "الطابع الزمني",
    "addTimelineEntry": "إضافة حدث",
    "associatedTimelineEntries": "إدخالات الجدول الزمني المرتبطة",
    "major": "رئيسي",
    "ongoing": "جارٍ",
    "detection": "الكشف",
    "severityChanged": "تم تغيير الخطورة",
    "resolution": "الحل",
    "closing": "الإغلاق",
    "dismissal": "الرفض",
    "statusChanged": "تم تغيير الحالة",
    "cannotDeleteAutoTimeline": "لا يمكن حذف إدخالات الجدول الزمني التلقائية",
    "reauthenticateForSensitiveAction": "الإجراء الذي تحاول تنفيذه حساس ويتطلب إعادة المصادقة",
    "timestampCannotBeInTheFuture": "لا يمكن أن يكون الطابع الزمني في المستقبل",
    "timelineEntry": "إدخال الجدول الزمني",
    "sampleTimeline": "الجدول الزمني",

    # Risk / findings misc
    "potentialThreats": "التهديدات المحتملة",
    "followUpUnresolvedHigh": "غير محلول بخطورة عالية أو حرجة",
    "edited": "محرَّر",
    "quickStart": "البداية السريعة",
    "getStarted": "ابدأ الآن",

    # Audit names
    "auditName": "اسم التدقيق",
    "riskAssessmentName": "اسم تقييم المخاطر",
    "noDataAvailable": "لا تتوفر بيانات كافية لهذا العرض. حدّث الصفحة عند توفر المزيد من المحتوى.",
    "etaOrCompletionDate": "تاريخ الاستحقاق/الاكتمال",
    "etaOrCompletionDateHelpText": "التاريخ المتوقع لإتمام المهمة أو تاريخ إتمامها الفعلي",
    "completionDateHelpText": "التاريخ الذي اكتملت فيه المهمة",

    # Recurrence
    "isRecurrent": "متكرر",
    "isRecurrentHelpText": "حدّد ما إذا كانت المهمة متكررة",
    "interval": "الفاصل الزمني",
    "each": "كل",
    "the": "الـ",
    "of": "من",
    "recurrent": "متكرر",
    "day": "يوم",
    "week": "أسبوع",
    "month": "شهر",
    "year": "سنة",
    "completed": "مكتمل",
    "first": "الأول",
    "second": "الثاني",
    "third": "الثالث",
    "fourth": "الرابع",
    "last": "الأخير",
    "taskDateHelpText": "تاريخ المهمة أو بداية تكرارها",
    "isTemplate": "متكرر",
    "taskNode": "تكرار المهمة",
    "taskNodes": "تكرارات المهام",
    "associatedTaskNodes": "التكرارات المرتبطة",
    "nextOccurrence": "التكرار التالي",
    "lastOccurrenceStatus": "حالة آخر تكرار",
    "weeksOfMonthErrorMessage": "يجب تحديد أسبوع واحد على الأقل لليوم (الأيام) المحددة",
    "daysOfWeekErrorMessage": "يجب تحديد يوم واحد على الأقل من أيام الأسبوع",
    "noEvents": "لا توجد أحداث لهذا اليوم",
    "taskNodeDuplicateDueDate": "توجد مهمة بالفعل لهذا النموذج في التاريخ المحدد. الرجاء اختيار تاريخ مختلف.",

    # Impact / control
    "impactHelpText": "تقدير تأثير الضابط",
    "selectAsset": "اختيار أصل",
    "allow_all": "السماح بالكل",
    "featureFlagSettingsUpdated": "تم تحديث إعدادات علامات الميزات. الرجاء تحديث الصفحة لتطبيق التغييرات.",

    # Domain analytics
    "domainAnalytics": "تحليلات النطاق",

    # Personal access tokens
    "personalAccessTokensDescription": "الرموز المميزة التي أنشأتها والتي يمكن استخدامها للوصول إلى واجهة برمجة تطبيقات منصة SICO GRC.",
    "personalAccessTokenCreateDescription": "يمكن استخدام رموز الوصول الشخصية (PATs) بدلاً من كلمة المرور للمصادقة على واجهة برمجة التطبيقات.",
    "personalAccessTokenCreateWarning": "تحذير: رموز الوصول الشخصية معلومات حساسة. تعامل معها ككلمات مرور. إذا فقدت رمزاً مميزاً، ستحتاج إلى إنشاء رمز جديد.",
    "personalAccessTokenOnlyDisplayedOnce": "سيُعرض الرمز مرة واحدة فقط. تأكد من نسخه وتخزينه بأمان.",
    "expiresOn": "ينتهي في {date}",
    "expiresIn": "ينتهي في",
    "copied": "تم النسخ!",
    "personalAccessTokenExpiryHelpText": "عدد الأيام التي ينتهي بعدها الرمز المميز",
    "successfullyDeletedPersonalAccessToken": "تم حذف رمز الوصول الشخصي بنجاح",
    "personalAccessTokenDeleteConfirm": "هل أنت متأكد من رغبتك في حذف رمز الوصول الشخصي هذا؟ لن تتمكن أي تطبيقات أو برامج نصية تستخدم هذا الرمز من الوصول إلى واجهة برمجة التطبيقات بعد الآن.",
    "errorCreatingPersonalAccessToken": "حدث خطأ أثناء إنشاء رمز الوصول الشخصي.",
    "errorMaxPatAmountExceeded": "تم تجاوز الحد الأقصى لعدد الرموز المسموح بها لهذا المستخدم.",

    # Sync / applied controls
    "theFollowingChangesWillBeApplied": "ستُطبَّق التغييرات التالية:",
    "syncToAppliedControlsMessage": "ستتم مزامنة تقييمات متطلبات هذا التدقيق مع حالة الضوابط المطبقة المرتبطة.",
    "syncToAppliedControlsSuccess": "اكتملت المزامنة بنجاح",
    "syncToAppliedControlsError": "فشلت المزامنة",
    "syncToAppliedControlsRiskScenarioMessage": "إذا كانت جميع الضوابط المطبقة الإضافية لهذا السيناريو نشطة، فسيتم نقلها إلى الضوابط الموجودة وإعادة تعيين التقييم المتبقي.",
    "syncToAppliedControlsRiskAssessmentMessage": "ستتم مزامنة السيناريوهات مع المستوى المتبقي بناءً على تقدم ضوابطها الإضافية.",
    "riskScenarioSyncWithChanges": "{ref_id} {name} - المستوى الحالي: {current_level} ➡️ {residual_level}",
    "theFollowingControlsWillBeMovedToExisting": "ستُنقل الضوابط التالية إلى الضوابط الموجودة في هذا السيناريو:",
    "resetResidual": "إعادة تعيين المخاطر المتبقية",
    "resetResidualHelpText": "سيؤدي تمكين هذا إلى إعادة تعيين مستوى المخاطر المتبقية، مما قد يساعد في الإعداد لتقييم جديد",

    # Risk matrix settings
    "settingsRiskMatrixSwapAxes": "تبديل المحاور",
    "settingsRiskMatrixSwapAxesHelpText": "يعكس محوري الاحتمالية والتأثير. عند التمكين، سيُعرض التأثير على المحور الرأسي والاحتمالية على المحور الأفقي.",
    "settingsRiskMatrixFlipVertical": "عكس رأسي",
    "settingsRiskMatrixFlipVerticalHelpText": "عند التمكين، سيكون أصل المصفوفة في الزاوية العلوية اليسرى مع زيادة محور Y نحو الأسفل.",
    "settingsRiskMatrix": "إعدادات مصفوفة المخاطر",

    # Batch / selection
    "changeStatus": "تغيير الحالة",
    "changeHealth": "تغيير فحص الصحة",
    "changeCsfFunction": "... وظيفة CSF",
    "clearSelection": "مسح التحديد",
    "itemsSelected": "{count} عنصر(عناصر) محدد(ة)",
    "batchActionConfirmDelete": "هل أنت متأكد من رغبتك في حذف {count} عنصر(عناصر)؟",
    "batchActionConfirmChange": "تطبيق على {count} عنصر(عناصر):",
    "batchActionSuccess": "تم التطبيق بنجاح على {count} عنصر(عناصر)",
    "batchActionAllFailed": "فشل الإجراء لجميع {count} عنصر(عناصر)",
    "batchActionPartialSuccess": "نجح {succeeded}، فشل {failed}",

    # Log / audit
    "logEntryRepr": "{timestamp} - {actor} - {action} - {object}",
    "objectRepr": "الكائن",
    "currentValue": "القيمة الحالية",
    "documentation": "التوثيق",
    "tests": "الاختبارات",
    "errorUpdatingObject": "حدث خطأ أثناء تحديث كائن {object}.",
    "logentry": "إدخال السجل",

    # Asset classes
    "assetClassDevices": "الأجهزة",
    "assetClassEnterpriseAssets": "الأصول المؤسسية",
    "assetClassEndUserDevices": "أجهزة المستخدم النهائي",
    "assetClassPortable": "محمول",
    "assetClassMobile": "محمول يدوي",
    "assetClassServers": "الخوادم",
    "assetClassCloudInfrastructure": "البنية التحتية السحابية",
    "assetClassIotAndNonComputingDevices": "أجهزة إنترنت الأشياء والأجهزة غير الحوسبية",
    "assetClassServices": "الخدمات",
    "assetClassAPIs": "واجهات برمجة التطبيقات",
    "assetClassSaas": "البرمجيات كخدمة",
    "assetClassOperatingSystems": "أنظمة التشغيل",
    "assetClassFirmware": "البرامج الثابتة",
    "assetClassData": "البيانات",
    "assetClassSensitiveData": "البيانات الحساسة",
    "assetClassLogData": "بيانات السجلات",
    "assetClassPhysicalData": "البيانات المادية",
    "assetClassWorkforce": "القوى العاملة",
    "assetClassServiceProviders": "مزودو الخدمة",
    "assetClassUserAccounts": "حسابات المستخدمين",
    "assetClassAdministratorAccounts": "حسابات المسؤولين",
    "assetClassServiceAccounts": "حسابات الخدمة",
    "assetClassNetworkInfrastructure": "البنية التحتية للشبكة",
    "assetClassNetworkArchitecture": "هندسة الشبكة",
    "assetClassDocumentation": "التوثيق",
    "assetClassPlans": "الخطط",
    "assetClassProcesses": "العمليات",
    "assetClassProcedures": "الإجراءات",
    "assetClassBusinessProcess": "العملية التجارية",
    "assetClassCoreOperations": "العمليات الأساسية",
    "assetClassProductOrServiceDevelopment": "تطوير المنتج أو الخدمة",
    "assetClassProductOrServiceDelivery": "تسليم المنتج أو الخدمة",
    "assetClassSalesAndMarketing": "المبيعات والتسويق",
    "assetClassCustomerService": "خدمة العملاء",
    "assetClassSupplyChainManagement": "إدارة سلسلة التوريد",
    "assetClassManagementAndGovernance": "الإدارة والحوكمة",
    "assetClassManagementAndGovernanceDescription": "أدوات لإدارة المشاريع والعقود والتحقق الداخلي.",
    "assetClassStrategicPlanning": "التخطيط الاستراتيجي",
    "assetClassFinancialManagement": "الإدارة المالية",
    "assetClassRiskManagement": "إدارة المخاطر",
    "assetClassComplianceManagement": "إدارة الامتثال",
    "assetClassPerformanceManagement": "إدارة الأداء",
    "assetClassSupportFunctions": "وظائف الدعم",
    "assetClassHumanResources": "الموارد البشرية",
    "assetClassFacilitiesManagement": "إدارة المرافق",
    "assetClassProcurement": "المشتريات",
    "assetClassLegalServices": "الخدمات القانونية",
    "assetClassAdministrativeServices": "الخدمات الإدارية",
    "assetClassExternalRelationships": "العلاقات الخارجية",
    "assetClassVendorManagement": "إدارة الموردين",
    "assetClassPartnerManagement": "إدارة الشركاء",
    "assetClassGovernmentRelations": "العلاقات الحكومية",
    "assetClassCommunityRelations": "العلاقات المجتمعية",
    "assetClassInvestorRelations": "علاقات المستثمرين",
    "assetClassFacilities": "المرافق",
    "assetClassPhysicalAccessPoint": "نقاط الوصول المادي",
    "assetClassArchivesRoom": "غرف الأرشيف",
    "assetClassPrimaryBuilding": "المبنى الرئيسي",
    "assetClassPhysicalSecuritySystem": "نظام الأمن المادي",
    "assetClassSafetySystem": "نظام السلامة",
    "assetClassExternalFacilities": "المبنى الخارجي",

    # Reporting / detection
    "reportedAt": "تاريخ الإبلاغ",
    "reportedAtHelpText": "الطابع الزمني للإبلاغ الفعلي",
    "detectedBy": "تم الكشف بواسطة",
    "internal": "داخلي",
    "external": "خارجي",
    "internallyDetected": "داخلي",
    "externallyDetected": "خارجي",

    # Campaign
    "campaignDomainHelpText": "النطاق الذي ستُرفق به الحملة.",
    "daysRemaining": "الأيام المتبقية",

    # OIDC / SSO
    "serverURL": "عنوان URL الخادم",
    "oidcConfiguration": "openid-configuration",
    "tokenAuthMethod": "طريقة مصادقة الرمز",
    "oauthPKCEEnabled": "OAuth PKCE مُمكَّن",
    "suggestedParentheses": "(مقترح)",
    "clientSecretAlreadySetHelpText": "تم ضبط سر العميل بالفعل.",
    "resetClientSecret": "إعادة تعيين سر العميل",
    "oidcTokenAuthMethodHelpText": "طريقة مصادقة نقطة نهاية الرمز الاختيارية. إذا لم تُحدَّد، تُستخدم طريقة من قائمة طرق الخادم.",
    "oidcPKCEEnabledHelpText": "تمكين دعم OAuth PKCE (مفتاح إثبات تبادل الكود). يُوصى به للعملاء العموميين.",

    # Data wizard
    "clickToUpload": "انقر للتحميل",
    "orDragAndDrop": "أو اسحب وأفلت",
    "dataWizardSelectFile": "اختر ملفك وتأكد من مطابقته للقوالب",
    "dataWizardChooseModel": "اختر النموذج المقابل",
    "dataWizardSelectScope": "اختر النطاق",
    "dataWizardClickUpload": "انقر على رفع",
    "fileAcceptExcelOnly": "ملفات Excel (.xls, .xlsx) فقط",
    "object": "الكائن",
    "dataWizardSelectFallbackDomain": "اختر نطاقاً احتياطياً (إذا لم يُحدَّد في الملف)",
    "dataWizardSelectPerimeter": "اختر محيطاً",
    "dataWizardSelectFramework": "اختر إطاراً",
    "dataWizardParsingResults": "نتائج التحليل:",
    "dataWizardTemplatesAndGuidelines": "القوالب والإرشادات",
    "dataWizardLoadExcelData": "تحميل بيانات Excel",
    "dataWizardSelectRiskMatrix": "اختر مصفوفة مخاطر",
    "dataWizardOnConflict": "إذا كان السجل موجوداً بالفعل",
    "dataWizardOnConflictSkip": "تخطي",
    "dataWizardOnConflictStopDescription": "إيقاف الاستيراد عند أول تعارض",
    "dataWizardOnConflictSkipDescription": "تجاهل المكررات، استيراد السجلات الجديدة فقط",

    # Inherent risk
    "inherentProba": "الاحتمالية الكامنة",
    "inherentImpact": "التأثير الكامن",
    "inherentLevel": "المستوى الكامن",
    "inherentRiskLevelPerScenario": "مستوى المخاطر الكامنة لكل سيناريو",
    "inherentRiskLevel": "مستوى المخاطر الكامنة",
    "inherentRiskLevelHelpText": "مستوى المخاطر قبل تطبيق أي ضوابط",

    # Campaigns / audits
    "associatedCampaigns": "الحملات المرتبطة",
    "recentlyUpdatedAudits": "التدقيقات المحدَّثة مؤخراً",

    # Quotation
    "quotationMethod": "طريقة التقدير",
    "quotationMethodSemiColon": "طريقة التقدير:",
    "manual": "يدوي",
    "express": "سريع",

    # Selectors
    "selectExisting": "اختيار موجود",
    "icon": "أيقونة",

    # Org / ISO
    "hideDomains": "إخفاء النطاقات",
    "defaultAssignee": "المسند إليه الافتراضي",
    "defaultAssigneeHelpText": "سيُعيَّن هذا الممثل تلقائياً كمؤلف لجميع تقييمات هذا المحيط",
    "riskToleranceHelpText": "حد مستوى المخاطر المقبولة",
    "withinTolerance": "ضمن الحد المقبول",
    "markdownHelpText": "يدعم Markdown: **غامق**، *مائل*، `كود`، [روابط](url)، قوائم، إلخ.",
    "markdownCTA": "انقر نقراً مزدوجاً لإضافة محتوى...",
    "organisationObjectives": "الأهداف (ISO)",
    "addOrganisationIssue": "إضافة مسألة",
    "organisationIssue": "مسألة",
    "organisationIssues": "المسائل (ISO)",
    "issues": "المسائل (ISO)",
    "organisationDescription": "هنا حيث تُحدد تسلسل المنظمة الهرمي ونطاقها.",
    "health": "فحص الصحة",
    "healthFieldHelpText": "يساعد في تتبع التقدم العام",
    "achieved": "محقق",
    "degraded": "متدهور",
    "offTrack": "خارج المسار",
    "isAssigned": "مسنَد",
    "past": "سابق",
    "isLocked": "مقفل",
    "isLockedHelpText": "قفل هذا التقييم لمنع التعديلات عليه وعلى العناصر المرتبطة به.",
    "lockedAssessment": "التقييم مقفل",
    "lockedAssessmentMessage": "هذا التقييم مقفل.",
    "lockedRiskScenarioMessage": "لا يمكن تعديل هذا السيناريو لأن تقييم المخاطر الأصلي مقفل.",
    "lockedRequirementAssessmentMessage": "لا يمكن تعديل هذا المتطلب لأن تقييم الامتثال الأصلي مقفل.",
    "assessmentInReview": "التقييم قيد المراجعة",
    "assessmentInReviewMessage": "هذا التقييم قيد المراجعة حالياً ولا يمكن تعديله.",
    "lockedFindingMessage": "لا يمكن تعديل هذه النتيجة لأن تقييم النتائج الأصلي مقفل.",
    "parentAssessmentLocked": "التقييم الأصلي مقفل",

    # Impact/effort matrix
    "impactEffortMatrixHint": "تلميح: يمكنك استخدام النقر بزر الماوس الأيمن للتبديل السريع لتقديرات التأثير والجهد. حدّث الصفحة لإعادة رسم المصفوفة",
    "resetFilter": "إعادة تعيين الفلتر",
    "noActiveFilter": "لا يوجد فلتر نشط",
    "showingAllAppliedControls": "عرض جميع الضوابط المطبقة",
    "showingItemsWith": "عرض العناصر مع",
    "qualificationsChartTitle": "تصنيفات سيناريوهات المخاطر",
    "saveAndNext": "حفظ والتالي",
    "priorityLegend": "المفتاح:",
    "quickWins": "مكاسب سريعة",
    "majorProjects": "مشاريع كبرى",
    "fillIns": "تعبئات",
    "questionable": "مثير للشك",

    # Project management
    "projectManagement": "إدارة المشاريع",
    "projectManagementDescription": "مجموعات بيانات عامة / الاعتمادات والشهادات",
    "genericCollections": "المجموعات",
    "relationship": "العلاقة",
    "relationships": "العلاقات",
    "crqStudies": "دراسات CRQ",
    "authority": "السلطة",
    "accredited": "معتمد",
    "notAccredited": "غير معتمد",
    "obsolete": "متقادم",
    "accreditationSimplified": "مبسط",
    "accreditationElaborated": "مفصَّل",
    "accreditationSensitive": "حساس",
    "accreditationRestricted": "مقيَّد",
    "accreditationAuthority": "جهة الاعتماد",
    "regulatoryAuthorityHelpText": "جهة من نوع 'جهة اعتماد'. يمكن تعريفها في قائمة الجهات",
    "contractor": "مقاول",
    "entityRelationship": "علاقة الجهة",

    # Evidences compliance
    "evidencesHelpText": "يعرض هذا الجدول جميع الأدلة المرتبطة بهذا التقييم، سواء مباشرة عبر تقييمات المتطلبات أو بشكل غير مباشر عبر الضوابط المطبقة.",
    "direct": "مباشر",
    "indirect": "غير مباشر",
    "viaAppliedControl": "عبر الضابط المطبق",
    "noEvidencesFound": "لم يُعثر على أدلة لهذا التقييم",
    "associatedOrganisationObjectives": "الأهداف المرتبطة",
    "evidenceRevisions": "المراجعات",
    "associatedEvidenceRevisions": "الإصدارات المرتبطة",

    # Context analysis
    "political": "سياسي",
    "economic": "اقتصادي",
    "social": "اجتماعي",
    "technology": "تكنولوجي",
    "organisationStructure": "هيكل المنظمة",
    "humanResources": "الموارد البشرية",
    "internalProcesses": "العمليات الداخلية",
    "financialCapacity": "الطاقة المالية",
    "companyCulture": "ثقافة الشركة / التواصل",

    # Quantitative risk hypotheses
    "associatedQuantitativeRiskHypotheses": "الفرضيات المرتبطة",
    "associatedQuantitativeRiskScenarios": "السيناريوهات المرتبطة",
    "lecChart": "مخطط LEC",
    "addedControls": "الضوابط المضافة",
    "removedControls": "الضوابط المحذوفة",
    "expectedLossLowerBound": "الحد الأدنى للخسارة المتوقعة (LB)",
    "expectedLossUpperBound": "الحد الأقصى للخسارة المتوقعة (UB)",
    "probabilityHelpText": "احتمالية تقديرية بين 0 و1 بناءً على المعرفة المتاحة",
    "lowerBoundHelpText": "الخسارة في أفضل سيناريو. 5٪ من الوقت قد تكون أقل من هذا.",
    "upperBoundHelpText": "الخسارة في أسوأ سيناريو. 5٪ من الوقت ستكون أعلى من هذا.",
    "simulationParameters": "معلمات المحاكاة",
    "simulationParametersDisplay": "معلمات المحاكاة",
    "lossAtPDiv4": "الخسارة عند P/4",
    "lossAtPDiv8": "الخسارة عند P/8",
    "loss_at_p_div_4": "الخسارة عند P/4",
    "loss_at_p_div_8": "الخسارة عند P/8",
    "addedAppliedControls": "الضوابط المضافة",
    "removedAppliedControls": "الضوابط المحذوفة",

    # Terminology
    "isVisible": "مرئي",
    "isVisibleHelpText": "إذا لم يكن مرئياً، لن يظهر هذا العنصر في القوائم ولن يكون قابلاً للاختيار، لكنه سيظل جزءاً من المصطلحات",
    "fieldPathHelpText": "الحقل الذي تحتاج إلى إضافة المصطلح إليه",
    "terminology": "مصطلح",
    "terminologies": "المصطلحات",
    "translations": "الترجمات",
    "translation": "الترجمة",
    "addTranslation": "إضافة ترجمة",
    "noTranslationAdded": "لم تُضف ترجمات بعد. انقر على 'إضافة ترجمة' للبدء",
    "translationErrorMessage": "اللغة والترجمة كلاهما مطلوبان",
    "selectLanguagePlaceholder": "اختر لغة...",
    "moreOnTerminologiesHelpText": "تلميح: يمكن تعريف المزيد من الخيارات عبر المصطلحات",

    # Cost / ROI
    "annualCostDisplay": "التكلفة السنوية",
    "amortizationPeriod": "فترة الاستهلاك (سنوات)",
    "amortizationPeriodHelpText": "الفترة التي سيُستهلَك خلالها تكلفة البناء",
    "buildCosts": "تكلفة البناء",
    "runCosts": "تكلفة التشغيل (سنوياً)",
    "fixedCost": "تكلفة ثابتة",
    "peopleDays": "أيام العمل",
    "implementationHelpText": "الأيام/الأشخاص اللازمة للتنفيذ",
    "oneTimeImplementationCost": "تكلفة التنفيذ لمرة واحدة",
    "annualOperationalCost": "التكلفة التشغيلية السنوية",
    "annualManDaysHelpText": "الأيام/الأشخاص المطلوبة سنوياً",
    "treatmentCost": "تكلفة المعالجة",
    "currentAle": "ALE الحالي",
    "currentAleDisplay": "ALE الحالي",
    "residualAle": "ALE المتبقي",
    "residualAleDisplay": "ALE المتبقي",
    "inherentAle": "ALE الكامن",
    "roc": "ROSI",
    "returnOnControls": "ROSI",
    "rocDisplay": "ROSI",
    "aleDisplay": "ALE",
    "treatmentCostDisplay": "تكلفة المعالجة",
    "rocInterpretation": "تفسير ROSI",
    "rocCalculationExplanation": "شرح ROSI",
    "rocHelpText": "العائد على الاستثمار الأمني - يُحسب كـ (ALE الحالي - ALE المتبقي - تكلفة المعالجة) / تكلفة المعالجة.",
    "isSimulationFresh": "بيانات المحاكاة محدَّثة",
    "simulationFresh": "بيانات المحاكاة محدَّثة",
    "simulationNotFresh": "بيانات المحاكاة غير محدَّثة - تغيرت المعلمات",
    "riskToleranceDisplay": "إعدادات تحمل المخاطر",
    "lossThresholdDisplay": "حد الخسارة",

    # Security capabilities
    "securityCapabilities": "القدرات الأمنية",
    "securityObjectivesTooltip": "تُحدَّد الأهداف الأمنية على الأصول الأولية وتُستنتج تلقائياً على الداعمة",
    "securityCapabilitiesTooltip": "تُحدَّد القدرات الأمنية على الأصول الداعمة وتُستنتج تلقائياً على الأولية",
    "disasterRecoveryObjectivesTooltip": "تُحدَّد أهداف الاسترداد على الأصول الأولية وتُستنتج تلقائياً على الداعمة",
    "recoveryCapabilitiesTooltip": "تُحدَّد قدرات الاسترداد على الأصول الداعمة وتُستنتج تلقائياً على الأولية",
    "expectation": "التوقع",
    "reality": "الواقع",
    "capability": "القدرة",
    "verdict": "الحكم",
    "alignment": "التوافق",
    "documented": "موثَّق",
    "tested": "مُختبَر",
    "objectivesMet": "الأهداف محققة",
    "objectivesNotMet": "الأهداف غير محققة",
    "noData": "لا توجد بيانات",
    "objectivesVsCapabilities": "الأهداف مقابل القدرات",
    "capabilities": "القدرات",
    "security": "الأمان",
    "recovery": "الاسترداد",
    "isSelectedHelpText": "حدد ما إذا كان ينبغي تضمينه في الدراسة",
    "quantRiskPriorityHelpText": "مفيد للمحلل لفرض ترتيب على الملخص التنفيذي",
    "lossThreshold": "حد الخسارة",
    "lossThresholdHelpText": "الحد الأقصى للخسارة المقبولة الذي سيُستخدم كأساس للتحمل",
    "missing": "مفقود",
    "hasMfaEnabled": "المصادقة الثنائية مُمكَّنة",

    # User management
    "userExpiryHelpText": "سيُعطَّل المستخدم بعد هذا التاريخ. المستخدمون الرئيسيون غير متأثرين.",
    "isSuperuser": "مستخدم رئيسي",

    # Table of contents
    "tableOfContents": "جدول المحتويات",
    "hideTableOfContents": "إخفاء جدول المحتويات",
    "jumpToSection": "الانتقال إلى القسم",
    "searchSections": "البحث في الأقسام...",
    "clearSearch": "مسح البحث",
    "noResultsFound": "لم يُعثر على أقسام",
    "goBackToControls": "العودة إلى الضوابط",
    "pathLabel": "المسار",

    # Executive summary / CRQ
    "executiveSummary": "الملخص التنفيذي",
    "keyMetrics": "المقاييس الرئيسية",
    "portfolioOverview": "نظرة عامة على المحفظة",
    "lossThresholdLabel": "حد الخسارة",
    "currentProfile": "الملف الحالي",
    "residualProfile": "الملف المتبقي",
    "riskReduction": "تخفيض المخاطر",
    "totalTreatmentCost": "إجمالي تكلفة المعالجة",
    "portfolioRiskProfile": "ملف مخاطر المحفظة",
    "currentAleCombined": "ALE الحالي - مجمَّع",
    "residualAleCombined": "ALE المتبقي - مجمَّع",
    "scenariosWith": "سيناريوهات",
    "lossExceedanceCurve": "منحنى تجاوز الخسارة",
    "riskScenariosAnalysis": "تحليل سيناريوهات المخاطر",
    "studyOverview": "نظرة عامة على الدراسة",
    "scenariosWithCurrentData": "السيناريوهات بالبيانات الحالية",
    "scenariosWithResidualData": "السيناريوهات بالبيانات المتبقية",
    "metricsDefinitions": "تعريفات المقاييس",
    "combinedLossExceedanceCurve": "منحنى تجاوز الخسارة المجمَّع",
    "combinedAleMetrics": "مقاييس ALE المجمَّعة",
    "noKeyMetricsAvailable": "لا تتوفر مقاييس رئيسية",
    "failedToLoadKeyMetrics": "فشل تحميل المقاييس الرئيسية",
    "errorLoadingData": "خطأ في تحميل البيانات",
    "controlsFromQuantitativeRisk": "الضوابط من الفرضيات",
    "retriggerAllSimulations": "إعادة تشغيل جميع المحاكاة",
    "simulationFailed": "فشلت المحاكاة: {errorMessage}",
    "allSimulationsCompletedSuccessfully": "اكتملت جميع المحاكاة بنجاح!",
    "simulationsCompletedWithFailures": "اكتملت المحاكاة مع {failedSimulations} إخفاقات من أصل {totalHypotheses} فرضيات",
    "allNSimulationsCompletedSuccessfully": "اكتملت جميع المحاكاة الـ {successfulSimulations} بنجاح!",
    "maximumAcceptableLoss": "الحد الأقصى للخسارة المقبولة",
    "probabilityToExceedThreshold": "احتمالية تجاوز الحد",
    "advancedAnalysisMetrics": "مقاييس التحليل المتقدمة لسيناريوهات المخاطر الكمية",
    "valueAtRisk": "القيمة المعرضة للخطر عند النسب المئوية المحددة",
    "probabilityExceedingThreshold": "احتمالية تجاوز حد الخسارة",
    "currentRiskWithExistingControls": "المخاطر مع الضوابط الموجودة",
    "residualRiskAfterTreatment": "المخاطر بعد تطبيق المعالجات المختارة",
    "noSimulationDataFound": "لم يُعثر على بيانات محاكاة لهذه الدراسة.",
    "thereWasAnErrorLoading": "حدث خطأ أثناء تحميل بيانات المقاييس الرئيسية.",
    "noSelectedScenarios": "لا توجد سيناريوهات محددة",
    "noScenariosSelectedInStudy": "لم يُحدَّد أي سيناريو في هذه الدراسة.",
    "failedToLoadExecutiveSummary": "فشل تحميل الملخص التنفيذي",
    "lossBreakdownByScenario": "توزيع الخسارة حسب السيناريو",
    "loadingExecutiveSummary": "جاري تحميل الملخص التنفيذي...",
    "loadingAleComparisonData": "جاري تحميل بيانات مقارنة ALE...",
    "totalScenarios": "إجمالي السيناريوهات",
    "withCurrentAle": "مع ALE الحالي",
    "withResidualAle": "مع ALE المتبقي",
    "withTreatmentCost": "مع تكلفة المعالجة",
    "noAleDataAvailable": "لا تتوفر بيانات ALE",
    "runSimulationsToGenerateAle": "قم بتشغيل المحاكاة على سيناريوهاتك لإنشاء بيانات مقارنة ALE.",
    "aleVsTreatmentCostByScenario": "ALE مقابل تكلفة المعالجة حسب السيناريو",
    "assumingIndependentScenarios": "بافتراض استقلالية السيناريوهات",
    "noLecDataAvailable": "لا تتوفر بيانات LEC. قم بتشغيل المحاكاة على فرضيات سيناريوهاتك.",
    "noAleDataAvailableRunSimulations": "لا تتوفر بيانات ALE. قم بتشغيل المحاكاة على سيناريوهاتك وفرضياتك.",
    "aleEvolutionTimeline": "الجدول الزمني لتطور ALE - تخفيض المخاطر من خلال تنفيذ المعالجات",
    "showHideColumns": "إظهار/إخفاء الأعمدة",
    "viewAleBreakdownByScenario": "عرض تفاصيل ALE حسب السيناريو",
    "combinedStudyRiskProfile": "ملف مخاطر الدراسة المجمَّع",
    "scenarioRiskProfile": "ملف مخاطر السيناريو",
    "breakdown": "التفاصيل",
    "detailedMetricsForEachRisk": "مقاييس تفصيلية لكل سيناريو مخاطر - انقر على رؤوس الأعمدة للترتيب",
    "columnsOfColumns": "من",
    "columns": "أعمدة",
    "hideAll": "إخفاء الكل",
    "legendNotes": "المفتاح والملاحظات",
    "legend": "المفتاح",
    "aleTimelineChartDebugInfo": "معلومات تصحيح مخطط ALE الزمني",
    "scenariosWithCurrentLevel": "السيناريوهات ذات المستوى الحالي:",
    "scenariosWithResidualLevel": "السيناريوهات ذات المستوى المتبقي:",
    "scenariosWithBothLevels": "السيناريوهات ذات كلا المستويين:",
    "scenariosWithTreatmentControls": "السيناريوهات ذات ضوابط المعالجة:",
    "viewRawScenarioData": "عرض بيانات السيناريو الخام",
    "cannotCalculate": "لا يمكن الحساب",
    "costYear": "التكلفة:",
    "additionalControls": "ضوابط إضافية",
    "andMore": "... و",
    "backToStudy": "العودة إلى الدراسة",
    "loadingKeyMetrics": "جاري تحميل المقاييس الرئيسية...",
    "retry": "إعادة المحاولة",
    "scenario": "السيناريو",
    "ale": "ALE",
    "var95": "VaR 95٪",
    "var99": "VaR 99٪",
    "var999": "VaR 99.9٪",
    "pThreshold": "P(>الحد)",
    "allLevels": "جميع المستويات",
    "filterByScenarioName": "تصفية بالاسم...",
    "filterByLevel": "تصفية بالمستوى...",
    "multipleResidualHypothesesHelp": "يمكن أن يكون لديك فرضيات متبقية (مستقبلية) متعددة لكن فرضية حالية (حاضرة) وفرضية كامنة (ماضية) واحدة فقط",
    "existingControlsHelp": "ما لديك حالياً. يُشكّل خط الأساس ولا يُحسب في تكلفة المعالجة.",
    "addedControlsHelp": "ما تحتاج إلى تنفيذه لتقليل المخاطر.",
    "removedControlsHelp": "مفيد لمحاكاة فرص توفير التكاليف أو وضعية المخاطر الكامنة",
    "probabilityP": "الاحتمالية (P)",
    "probabilityPercent": "الاحتمالية (٪)",
    "probabilityPercentHelpText": "احتمالية تقديرية بين 0 و100 (نسبة مئوية) بناءً على المعرفة المتاحة",
    "expectedLossLowerBoundCurrency": "الحد الأدنى للخسارة المتوقعة ({currency})",
    "expectedLossUpperBoundCurrency": "الحد الأقصى للخسارة المتوقعة ({currency})",
    "retriggerAllSimulationsTitle": "إعادة تشغيل جميع المحاكاة لهذه الدراسة بما فيها الفرضيات وبيانات المحفظة ومنحنى تحمل المخاطر",
    "costPerYear": "/سنة",
    "lossAmount": "مقدار الخسارة",
    "exceedanceProbability": "احتمالية التجاوز",
    "currentRiskExceedsTolerance": "المخاطر الحالية تتجاوز الحد المقبول",
    "currentRiskWithinTolerance": "المخاطر الحالية ضمن الحد المقبول",
    "residualRiskExceedsTolerance": "المخاطر المتبقية تتجاوز الحد المقبول",
    "residualRiskWithinTolerance": "المخاطر المتبقية ضمن الحد المقبول",
    "uniqueControl": "ضابط فريد",
    "uniqueControls": "ضوابط فريدة",
    "currentLabel": "الحالي",
    "noLecDataAvailableForScenario": "لا تتوفر بيانات LEC لهذا السيناريو",
    "runSimulationsOnHypotheses": "قم بتشغيل المحاكاة على الفرضيات لإنشاء المخططات",
    "selectScenariosToSeeSummary": "حدد السيناريوهات لرؤية الملخص التنفيذي",
    "thereWasAnErrorLoadingExecutive": "حدث خطأ أثناء تحميل بيانات الملخص التنفيذي",
    "anUnexpectedErrorOccurred": "حدث خطأ غير متوقع أثناء تحميل الملخص التنفيذي",
    "failedToLoadAleComparison": "فشل تحميل بيانات مقارنة ALE",
    "noCombinedLecDataAvailable": "لا تتوفر بيانات LEC مجمَّعة. قم بتشغيل المحاكاة على فرضيات سيناريوهاتك.",
    "compareHypotheses": "مقارنة الفرضيات",
    "lossExceedanceCurves": "منحنيات تجاوز الخسارة",
    "noCurveDataAvailable": "لا تتوفر بيانات المنحنى. قم بتشغيل المحاكاة على فرضياتك.",
    "combinedCurrentRisk": "المخاطر الحالية المجمَّعة",

    # Graph explorer
    "noMatchingNodesFound": "لم يُعثر على عقد مطابقة",
    "findANode": "البحث عن عقدة...",
    "viewOnGraphExplorer": "عرض في مستكشف الرسم البياني",
    "visualizeAppliedMapping": "تصوير بيانات التعيين المطبقة كرسم بياني",
    "frameworksMapping": "تعيين الأطر",
    "assetsExplorer": "مستكشف الأصول",
    "visualizeAssetsRelationships": "تصوير الأصول وعلاقاتها",
    "requirementsExplorer": "مستكشف المتطلبات",
    "visualizeRequirements": "تصوير جميع المتطلبات عبر جميع عمليات التدقيق",
    "assessable": "قابل للتقييم",

    # Permission/model display
    "permissionDisplay": "{operation} {model}",
    "event": "حدث",
    "logentry": "إدخال السجل",

    # Vulnerabilities
    "vulnerabilityDistribution": "توزيع الثغرات الأمنية",
    "visualizeButton": "تصوير الثغرات",
    "vulnerabilityTreemap": "خريطة شجرة الثغرات",
    "hierarchicalViewDomainsToSeverityToStatus": "عرض هرمي: النطاقات → الخطورة → الحالة",
    "filterVulnerabilitiesBySeverity": "تصفية الثغرات حسب الخطورة",
    "filterVulnerabilitiesByStatus": "تصفية الثغرات حسب الحالة",
    "noDataMatchesFilters": "لا توجد بيانات تطابق الفلاتر المحددة",
    "clickToDrillDown": "انقر للتعمق",
    "failedToLoadVulnerabilityData": "فشل تحميل بيانات الثغرات",
    "noQualificationsFoundOnRiskScenarios": "لم يُعثر على تصنيفات لسيناريوهات المخاطر",
    "errorLoadingVulnerabilityData": "خطأ في تحميل بيانات الثغرات",
    "findingsAssessmentDistribution": "توزيع تقييمات النتائج",

    # Change/delete/view CRUD for extra models
    "changeDataRecipient": "تغيير متلقي البيانات",
    "changeDataSubject": "تغيير موضوع البيانات",
    "changeEscalationThreshold": "تغيير حد التصعيد",
    "changeOperatingMode": "تغيير وضع التشغيل",
    "changeOperationalScenario": "تغيير السيناريو التشغيلي",
    "changeOrganisationIssue": "تغيير مسألة المنظمة",
    "changePersonalData": "تغيير البيانات الشخصية",
    "changeRepresentative": "تغيير الممثل",
    "changeTimelineEntry": "تغيير إدخال الجدول الزمني",
    "deleteDataRecipient": "حذف متلقي البيانات",
    "deleteDataSubject": "حذف موضوع البيانات",
    "deleteEscalationThreshold": "حذف حد التصعيد",
    "deleteOperatingMode": "حذف وضع التشغيل",
    "deleteOperationalScenario": "حذف السيناريو التشغيلي",
    "deleteOrganisationIssue": "حذف مسألة المنظمة",
    "deletePersonalData": "حذف البيانات الشخصية",
    "deleteRepresentative": "حذف الممثل",
    "deleteTimelineEntry": "حذف إدخال الجدول الزمني",
    "viewDataRecipient": "عرض متلقي البيانات",
    "viewDataSubject": "عرض موضوع البيانات",
    "viewEscalationThreshold": "عرض حد التصعيد",
    "viewOperatingMode": "عرض وضع التشغيل",
    "viewOperationalScenario": "عرض السيناريو التشغيلي",
    "viewOrganisationIssue": "عرض مسألة المنظمة",
    "viewPersonalData": "عرض البيانات الشخصية",
    "viewRepresentative": "عرض الممثل",
    "viewTimelineEntry": "عرض إدخال الجدول الزمني",

    # Model names
    "HistoricalMetric": "مقياس تاريخي",
    "FlowEvent": "حدث تدفق",
    "AssetCapability": "قدرة الأصل",
    "dataFlowOverview": "نظرة عامة على تدفق البيانات",

    # Jira integration
    "serverUrl": "عنوان URL الخادم",
    "projectKey": "مفتاح المشروع",
    "apiToken": "رمز API",
    "webhookUrl": "عنوان URL للـ Webhook",
    "webhookSecret": "سر الـ Webhook",
    "jiraServerUrlHelpText": "عنوان URL لخادم Jira (مثال: https://example.atlassian.net/).",
    "jiraEmailHelpText": "عنوان البريد الإلكتروني المرتبط بحساب خدمة Jira.",
    "jiraProjectKeyHelpText": "مفتاح مشروع Jira الذي ستُنشأ فيه المشكلات (مثال: 'SEC').",
    "jiraIntegrationConfig": "تهيئة تكامل Jira",
    "apiTokenAlreadySetHelpText": "تم ضبط رمز API بالفعل.",
    "webhookSecretAlreadySetHelpText": "تم ضبط سر الـ Webhook بالفعل.",
    "resetApiToken": "إعادة تعيين رمز API",
    "resetWebhookSecret": "إعادة تعيين سر الـ Webhook",
    "testConnection": "اختبار الاتصال",
    "connectionSuccessful": "الاتصال ناجح",
    "connectionFailed": "فشل الاتصال",
    "overlapWithOtherFrameworks": "تداخل مع أطر أخرى",
    "spPrivateKeyAlreadySetHelpText": "تم ضبط مفتاح خاص بالفعل. لأسباب أمنية لا يمكنك الاطلاع عليه مجدداً، يمكنك فقط استبداله بمفتاح جديد.",
    "resetSpPrivateKey": "إعادة تعيين المفتاح الخاص",
    "hideEmptySections": "إخفاء الأقسام الفارغة",
    "includeTeamAssignments": "تضمين إسنادات الفريق",
    "directAssignmentsOnly": "الإسنادات المباشرة فقط",
    "outgoingSync": "مزامنة صادرة",
    "incomingSync": "مزامنة واردة",
    "failed": "فشل",
    "conflict": "تعارض",
    "syncedWith": "تمت المزامنة مع {integrationName}",
    "remoteId": "المعرف البعيد",
    "lastSynced": "آخر مزامنة",
    "integrationProvider": "مزود التكامل",
    "integrationProviderHelpText": "اختر مزود التكامل لتهيئة المزامنة على مستوى الكائن",
    "remoteObject": "الكائن البعيد",
    "remoteObjectHelpText": "اختر الكائن البعيد للمزامنة معه",
    "webhookEndpointUrl": "عنوان URL لنقطة نهاية Webhook",
    "webhookEndpointUrlHelpText": "عنوان URL الذي سيتلقى التطبيق فيه الـ Webhooks الواردة.",
    "createRemoteObject": "إنشاء كائن بعيد",
    "createRemoteObjectHelpText": "عند التمكين، سيُنشأ كائن مقابل في الخدمة الخارجية عند إنشاء هذا العنصر.",

    # Metrics
    "metricInstance": "مثيل المقياس",
    "metricInstances": "مثيلات المقاييس",
    "customMetricSample": "عينة مقياس مخصص",
    "customMetricSamples": "عينات مقاييس مخصصة",
    "builtinMetricSample": "عينة مقياس مدمج",
    "builtinMetricSamples": "عينات مقاييس مدمجة",
    "metricType": "نوع المقياس",
    "customMetric": "مقياس مخصص",
    "builtinMetric": "مقياس مدمج",
    "targetObjectType": "نوع الكائن",
    "targetObject": "الكائن المستهدف",
    "metricUnit": "وحدة المقياس",

    # Dashboards
    "dashboards": "لوحات القيادة",
    "dashboardDefinition": "تعريف لوحة القيادة",
    "dashboardWidget": "عنصر واجهة",
    "dashboardWidgets": "عناصر واجهة",
    "addDashboardWidget": "إضافة عنصر",
    "widgets": "العناصر",
    "addWidget": "إضافة عنصر",
    "addRow": "إضافة صف",
    "removeRow": "إزالة صف",
    "addFirstWidget": "إضافة أول عنصر",
    "noWidgetsYet": "لم تُهيَّأ أي عناصر واجهة لهذه اللوحة بعد.",
    "chartType": "نوع المخطط",
    "timeRange": "النطاق الزمني",
    "aggregation": "التجميع",
    "positionX": "الموضع X",
    "positionY": "الموضع Y",
    "width": "العرض",
    "height": "الارتفاع",
    "widgetConfig": "تهيئة العنصر",
    "actual": "الفعلي",
    "remaining": "المتبقي",
    "pieChart": "مخطط دائري",
    "donutChart": "مخطط كعكة",
    "textContent": "محتوى نصي",
    "addTextWidget": "إضافة نص",
    "editLayout": "العناصر",
    "editAttributes": "السمات",
    "dashboardEditorInstructions": "اسحب العناصر لإعادة ترتيبها. استخدم مقابض تغيير الحجم لتغيير الحجم. انقر على حفظ للاحتفاظ بالتغييرات.",
    "layoutSaved": "تم حفظ التخطيط بنجاح",
    "collectionFrequency": "تكرار الجمع",
    "targetValue": "القيمة المستهدفة",
    "minValue": "الحد الأدنى للقيمة",
    "maxValue": "الحد الأقصى للقيمة",
    "choicesDefinition": "تعريف الخيارات",
    "higherIsBetter": "الأعلى أفضل",
    "higherIsBetterHelpText": "إذا تم التحديد، فإن الزيادة في القيمة إيجابية (مثال: نتيجة الامتثال). إذا لم يتم التحديد، فإن الانخفاض إيجابي (مثال: عدد الثغرات).",
    "defaultTarget": "الهدف الافتراضي",
    "defaultTargetHelpText": "القيمة المستهدفة الافتراضية لمثيلات المقاييس. يمكن تجاوزها على مستوى المثيل.",

    # Library mappings
    "mappingLibraries": "مكتبات التعيين",
    "importedFrameworks": "الأطر المستوردة",
    "notImportedFrameworks": "الأطر غير المستوردة",

    # Convert to quantitative
    "convertToQuantitative": "تحويل إلى كمي",
    "convertToQuantitativeRisk": "التحويل إلى تقييم مخاطر كمي",
    "convertToQuantitativeRiskDescription": "قدم نقاط ارتكاز لتحويل تقييم المخاطر النوعي هذا إلى دراسة كمية بمحاكاة مونت كارلو.",
    "sourceRiskAssessment": "تقييم المخاطر المصدر",
    "probabilityAnchoring": "ربط الاحتمالية",
    "probabilityAnchoringDescription": "عيّن كل مستوى احتمالية لقيمة نسبة مئوية بين 0 و100.",
    "impactAnchoring": "ربط التأثير",
    "impactAnchoringDescription": "لكل مستوى تأثير، قدم قيمة خسارة مالية نموذجية.",
    "lowerBound": "الحد الأدنى",
    "upperBound": "الحد الأقصى",
    "lossThresholdDescription": "الحد الأقصى للخسارة المقبولة لدراسة المخاطر الكمية.",
    "converting": "جاري التحويل...",
    "conversionSuccessful": "تم التحويل بنجاح! جاري إعادة التوجيه إلى دراسة المخاطر الكمية الجديدة...",
    "conversionFailed": "فشل التحويل. الرجاء التحقق من المدخلات والمحاولة مجدداً.",
    "pleaseProvideAtLeastOneProbabilityAnchor": "الرجاء تقديم قيمة ربط احتمالية واحدة على الأقل.",
    "pleaseProvideAtLeastOneImpactAnchor": "الرجاء تقديم قيمة ربط تأثير واحدة على الأقل.",
    "pleaseProvideValidLossThreshold": "الرجاء تقديم قيمة حد خسارة صحيحة أكبر من 0.",
    "allProbabilityValuesMustBeProvided": "يجب تقديم جميع قيم الاحتمالية.",
    "allImpactValuesMustBeProvided": "يجب تقديم جميع قيم التأثير.",
    "probabilityMustBeBetweenZeroAndOne": "يجب أن تكون احتمالية '{level}' بين 0 و1.",
    "probabilityMustBeBetweenZeroAndHundred": "يجب أن تكون احتمالية '{level}' بين 0 و100.",
    "probabilityValuesMustBeIncreasing": "يجب أن تكون احتمالية '{current}' أكبر من '{previous}'.",
    "impactMustBeGreaterThanZero": "يجب أن يكون تأثير '{level}' أكبر من 0.",
    "impactValuesMustBeIncreasing": "يجب أن يكون تأثير '{current}' أكبر من '{previous}'.",
    "runningMonteCarloSimulations": "جاري تشغيل محاكاة مونت كارلو لتحليل المخاطر الكمية...",
    "probabilityRequirements": "يجب تقديم جميع القيم وتكون بين 0 و100. يجب أن تتزايد القيم من أعلى إلى أسفل.",
    "impactRequirements": "يجب تقديم جميع القيم وأن تكون أكبر من 0. يجب أن تتزايد القيم من أعلى إلى أسفل.",

    # Webhooks
    "webhooks": "Webhooks",
    "webhooksDescription": "التكامل مع الأنظمة الخارجية عبر Webhooks",
    "webhookEndpoint": "نقطة نهاية Webhook",
    "webhookEndpoints": "نقاط نهاية Webhook",
    "url": "URL",
    "events": "الأحداث",
    "webhookSecretHelpText": "السر المشترك المستخدم لتوقيع حمولة Webhook للتحقق.",
    "secretAlreadySetHelpText": "تم ضبط السر بالفعل.",
    "resetSecret": "إعادة تعيين السر",
    "webhookSharedSecretShownOnce": "يُعرض السر المشترك مرة واحدة فقط عند الإنشاء. تأكد من نسخه وتخزينه بأمان.",
    "targetDomains": "النطاقات المستهدفة",
    "webhookEndpointTargetDomainsHelpText": "اختر النطاقات التي ستُشغَّل لها نقطة نهاية Webhook هذه. إذا لم يُختر أي نطاق، سيتم التشغيل لجميع النطاقات.",
    "thin": "رفيع",
    "payloadFormat": "تنسيق الحمولة",
    "payloadFormatHelpText": "اختر تنسيق حمولة Webhook.",

    # DORA
    "doraSpecific": "خاص بـ DORA",
    "doraEntityType": "نوع الجهة",
    "doraEntityHierarchy": "تسلسل الجهة الهرمي",
    "doraAssetsValue": "قيمة إجمالي الأصول",
    "doraCompetentAuthority": "الجهة المختصة",
    "doraProviderPersonType": "نوع الشخص",
    "doraContractualArrangement": "نوع العقد",
    "doraIctServiceType": "نوع خدمة تقنية المعلومات والاتصالات",
    "overarchingContract": "العقد الشامل",
    "overarchingContractHelpText": "تُعرض فقط العقود من نوع 'الترتيب الشامل'. إذا كانت القائمة فارغة، أنشئ عقداً شاملاً أولاً.",
    "annualExpense": "النفقة السنوية",
    "terminationReason": "سبب الإنهاء",
    "governingLawCountry": "بلد القانون الحاكم",
    "isIntragroup": "داخل المجموعة",
    "noticePeriodEntity": "مهلة الإشعار للجهة (أيام)",
    "noticePeriodProvider": "مهلة الإشعار للمزود (أيام)",
    "storageOfData": "يخزن بيانات",
    "dataLocationStorage": "موقع البيانات في حالة السكون",
    "dataLocationProcessing": "موقع البيانات أثناء المعالجة",
    "doraDataSensitiveness": "حساسية البيانات",
    "doraRelianceLevel": "مستوى الاعتماد",
    "doraSubstitutability": "قابلية الاستبدال",
    "doraNonSubstitutabilityReason": "سبب عدم قابلية الاستبدال",
    "doraHasExitPlan": "خطة الخروج",
    "doraReintegrationPossibility": "إمكانية إعادة الاندماج",
    "doraAlternativeProvidersIdentified": "تم تحديد مزودين بديلين",
    "doraAlternativeProviders": "المزودون البديلون",
    "doraAttributes": "سمات DORA",
    "doraAssessment": "تقييم DORA",
    "deleted": "محذوف",

    # Descriptions for modules
    "riskAssessmentsDescription": "تقييم وإدارة المخاطر باستخدام نهج مبسط وفق 27005",
    "ebiosRmDescription": "دراسات مبنية على منهجية EBIOS Risk Manager",
    "complianceAssessmentsDescription": "تقييم الامتثال للأطر التنظيمية",
    "appliedControlsDescription": "الضوابط الأمنية المطبقة في مؤسستك",
    "assetsDescription": "العمليات والوظائف التجارية (أولية)، التطبيقات أو المكونات التقنية (داعمة)",
    "threatsDescription": "التهديدات المحتملة لمؤسستك",
    "vulnerabilitiesDescription": "الثغرات الأمنية والنقاط الضعيفة المعروفة",
    "riskScenariosDescription": "سجل المخاطر مع السيناريوهات ومعالجاتها",
    "referenceControlsDescription": "قالب من الضوابط الأمنية النموذجية",
    "requirementMappingSetsDescription": "التعيينات بين الأطر والمعايير المختلفة",
    "riskMatricesDescription": "مصفوفات المخاطر لتقييم الاحتمالية والتأثير",
    "businessImpactAnalysisDescription": "تحليل الأثر التجاري وتخطيط الاستمرارية",
    "incidentsDescription": "الحوادث الأمنية وإدارتها",
    "taskTemplatesDescription": "مهام لمرة واحدة أو دورية لتنظيم الضوابط",
    "policiesDescription": "السياسات والإجراءات التنظيمية",
    "organisationIssuesDescription": "إدارة مسائل ISO 27001",
    "frameworksDescription": "أطر الأمن والامتثال",
    "foldersDescription": "الهيكل التنظيمي والنطاقات",
    "usersDescription": "حسابات المستخدمين وإدارة الوصول",
    "entitiesDescription": "الجهات الخارجية وعلاقاتها",
    "solutionsDescription": "الحلول التقنية المقدمة من الجهات",
    "accreditationsDescription": "الاعتمادات والشهادات",
    "assetAssessmentsDescription": "تقييم مرونة الأصول",
    "entityAssessmentsDescription": "تقييمات أمن الجهات الخارجية",
    "findingsAssessmentsDescription": "إدارة النتائج (اختبار الاختراق، التدقيق الداخلي، إلخ.)",
    "requirementAssessmentsDescription": "تقييم وتتبع المتطلبات",
    "operationalScenariosDescription": "السيناريوهات التشغيلية (EBIOS RM)",
    "stakeholdersDescription": "أصحاب المصلحة وعلاقاتهم (EBIOS RM)",
    "processingsDescription": "أنشطة معالجة البيانات (GDPR)",
    "quantitativeRiskHypothesesDescription": "الفرضيات للتحليل الكمي للمخاطر",
    "quantitativeRiskScenariosDescription": "السيناريوهات للتحليل الكمي للمخاطر",
    "quantitativeRiskStudiesDescription": "الدراسات الكمية للمخاطر والمحاكاة",
    "syncMappingsDescription": "تعيينات مزامنة الأطر",
    "genericCollectionsDescription": "مجموعات البيانات العامة",
    "perimetersDescription": "المحيطات الوظيفية لدراساتك",
    "organisationObjectivesDescription": "إدارة أهداف ISO 27001",
    "riskAcceptancesDescription": "قرارات قبول المخاطر والموافقات",
    "securityExceptionsDescription": "تتبع الاستثناءات والإعفاءات",
    "evidencesDescription": "الأدلة والوثائق الداعمة",
    "representativesDescription": "ممثلو الموردين",
    "contractsDescription": "العقود والاتفاقيات",
    "personalDataDescription": "مخزون البيانات الشخصية وتصنيفها",
    "purposesDescription": "أغراض معالجة البيانات (GDPR)",
    "rightRequestsDescription": "طلبات حقوق موضوع البيانات (GDPR)",
    "dataBreachesDescription": "حوادث اختراق البيانات والإشعارات",
    "gdprDescription": "ميزات إدارة حماية البيانات والخصوصية (امتثال GDPR)",

    # Ordered entry list
    "orderedEntryListAddNewEntry": "إضافة إدخال جديد",
    "orderedEntryListRefIdPlaceholder": "معرف المرجع",
    "orderedEntryListEmptyState": "لا توجد إدخالات بعد. أضف واحداً أعلاه!",
    "orderedEntryListDeleteAriaLabel": "حذف إدخال",
    "orderedEntryListDebugTitle": "تصحيح - مخرجات JSON",
    "orderedEntryListRefIdLabel": "معرف المرجع:",
    "orderedEntryListNameLabel": "الاسم:",

    # Misc
    "choices": "خيارات",
    "number": "رقم",
    "choiceLevel": "مستوى الخيار",

    # Search / resources
    "searchResourcesPlaceholder": "البحث في الموارد...",
    "noResourceMatchQuery": "لم يُعثر على مورد يطابق استعلامك.",

    # Yearly tasks review
    "yearlyTasksReview": "مراجعة المهام المجمَّعة",
    "startPeriod": "بداية الفترة",
    "endPeriod": "نهاية الفترة",
    "allFolders": "جميع النطاقات",
    "periodTo": "إلى",
    "noRecurrentTasksFound": "لم يُعثر على مهام متكررة",

    # Lowercase CRUD variants (duplicate with camelCase but different key)
    "addEscalationthreshold": "إضافة حد تصعيد",
    "addEvent": "إضافة حدث",
    "addOperatingmode": "إضافة وضع تشغيل",
    "addOrganisationissue": "إضافة مسألة منظمة",
    "addTimelineentry": "إضافة إدخال جدول زمني",
    "changeDatarecipient": "تغيير متلقي البيانات",
    "changeDatasubject": "تغيير موضوع البيانات",
    "changeEscalationthreshold": "تغيير حد التصعيد",
    "changeEvent": "تغيير الحدث",
    "changeKillchain": "تغيير kill chain",
    "changeOperatingmode": "تغيير وضع التشغيل",
    "changeOperationalscenario": "تغيير السيناريو التشغيلي",
    "changeOrganisationissue": "تغيير مسألة المنظمة",
    "changePersonaldata": "تغيير البيانات الشخصية",
    "changeTimelineentry": "تغيير إدخال الجدول الزمني",
    "deleteDatarecipient": "حذف متلقي البيانات",
    "deleteDatasubject": "حذف موضوع البيانات",
    "deleteEscalationthreshold": "حذف حد التصعيد",
    "deleteEvent": "حذف الحدث",
    "deleteKillchain": "حذف kill chain",
    "deleteOperatingmode": "حذف وضع التشغيل",
    "deleteOperationalscenario": "حذف السيناريو التشغيلي",
    "deleteOrganisationissue": "حذف مسألة المنظمة",
    "deletePersonaldata": "حذف البيانات الشخصية",
    "deleteTimelineentry": "حذف إدخال الجدول الزمني",
    "viewDatarecipient": "عرض متلقي البيانات",
    "viewDatasubject": "عرض موضوع البيانات",
    "viewEscalationthreshold": "عرض حد التصعيد",
    "viewEvent": "عرض الحدث",
    "viewKillchain": "عرض kill chain",
    "viewOperatingmode": "عرض وضع التشغيل",
    "viewOperationalscenario": "عرض السيناريو التشغيلي",
    "viewOrganisationissue": "عرض مسألة المنظمة",
    "viewPersonaldata": "عرض البيانات الشخصية",
    "viewTimelineentry": "عرض إدخال الجدول الزمني",

    # ServiceNow
    "serviceNowIntegrationConfig": "تهيئة تكامل ServiceNow",
    "serviceNowInstanceUrlHelpText": "عنوان URL لمثيل ServiceNow (مثال: https://example.service-now.com/).",
    "serviceNowUsernameHelpText": "اسم مستخدم حساب ServiceNow الخاص بك.",
    "serviceNowTableHelpText": "اختر جدول ServiceNow للمزامنة معه.",
    "instanceUrl": "عنوان URL للمثيل",
    "username": "اسم المستخدم",
    "passwordAlreadySetHelpText": "تم ضبط كلمة مرور المثيل بالفعل.",
    "tableName": "اسم الجدول",
    "baseQuery": "الاستعلام الأساسي",
    "globalOverall": "الإجمالي العام",
    "metricDefinitionsDescription": "تعريف مقاييس مخصصة لتتبع وقياس مؤشرات الأداء",
    "metricInstancesDescription": "تتبع قيم مقاييس محددة للكائنات في مؤسستك",
    "dashboardsDescription": "لوحات قيادة مخصصة لتصوير المقاييس ومؤشرات الأداء",
    "targetTable": "الجدول المستهدف",
    "serviceNowIntegrationMappingsDescription": "تعيينات مزامنة ServiceNow",
    "serviceNowIntegrationMappingsHelpText": "عيّن ضوابطك المحلية لسجلات ServiceNow.",
    "fieldMapping": "تعيين الحقول",
    "localField": "الحقل المحلي",
    "serviceNowColumn": "عمود ServiceNow",
    "valueMapping": "تعيين القيم",
    "valueMappingForField": "تعيين {field}",
    "valueMappingToField": "معيَّن_إلى: {field}",
    "secretCopiedToClipboard": "تم نسخ السر إلى الحافظة بنجاح",
    "lastRefresh": "آخر تحديث",
    "widgetCount": "عدد العناصر",

    # Teams
    "teams": "الفرق",
    "teamEmail": "البريد الإلكتروني للفريق",
    "leader": "القائد",
    "deputies": "النواب",
    "members": "الأعضاء",
    "jumpTo": "الانتقال إلى",

    # Assignment flow
    "assignmentStatusSubmitted": "مقدَّم",
    "assignmentStatusChangesRequested": "تم طلب تغييرات",
    "activateAll": "بدء الكل",
    "submitForReview": "إرسال للمراجعة",
    "submitForReviewConfirm": "هل أنت متأكد من رغبتك في إرسال إجاباتك للمراجعة؟ لن تتمكن من تعديلها حتى يعيدها المراجع.",
    "reopenAssignment": "إعادة فتح",
    "reviewerObservation": "ملاحظة المراجع",
    "reviewerObservationPlaceholder": "صف التغييرات المطلوبة...",
    "assignmentSubmittedBanner": "تم إرسال إجاباتك وهي قيد المراجعة.",
    "assignmentClosedBanner": "تم إغلاق هذا الإسناد من قبل المراجع.",
    "assignmentChangesRequestedBanner": "طلب المراجع تغييرات على إجاباتك.",
    "assignmentAwaitingStart": "لم يبدأ بعد",
    "reviewResponses": "مراجعة الإجابات",
    "incompleteAssessmentWarning": "{remaining} من {total} عنصر قابل للتقييم لا يزال بحاجة إلى تقييم",
    "incompleteAssessmentError": "يجب تقييم جميع العناصر القابلة للتقييم قبل الإرسال",

    # Comments
    "commentPlaceholder": "اكتب تعليقاً...",
    "commentEdited": "محرَّر",
    "markAsProcessed": "تحديد كمعالَج",
    "markAsActive": "تحديد كنشط",
    "noComments": "لا توجد تعليقات بعد",
    "deleteCommentConfirmation": "هل أنت متأكد من رغبتك في حذف هذا التعليق؟",
    "postComment": "نشر",
    "justNow": "للتو",
    "minutesAgo": "منذ {count} دقيقة",
    "hoursAgo": "منذ {count} ساعة",
    "daysAgo": "منذ {count} يوم",
    "processed": "معالَج",
    "hideProcessed": "إخفاء المعالَجة",
    "ctrlEnterToPost": "Ctrl+Enter للنشر",

    # Presets / journeys
    "presets": "المسارات",
    "presetsDescription": "اتبع مسارات موجهة لإعداد برنامجك الأمني خطوة بخطوة.",
    "availablePresets": "القوالب المتاحة",
    "activeJourneys": "المسارات النشطة",
    "applyPreset": "بدء مسار",
    "applyPresetConfirm": "اختر مكان إنشاء كائنات المسار.",
    "presetFeatureFlagsWarning": "سيؤدي تطبيق هذا القالب إلى ضبط الميزات المرئية في الشريط الجانبي.",
    "deleteJourney": "حذف المسار",
    "deleteJourneyConfirm": "هل أنت متأكد من رغبتك في حذف هذا المسار؟ لن يتم حذف الكائنات التي أنشأها النموذج.",
    "useExistingDomain": "استخدام نطاق موجود",
    "domainName": "اسم النطاق",
    "presetApplied": "تم تطبيق القالب بنجاح",
    "journeyDashboard": "لوحة قيادة المسار",
    "markAsSkipped": "تخطي",
    "notStarted": "لم يبدأ",
    "skipped": "مُتجاوَز",
    "folderName": "اسم النطاق",
    "stepsCompleted": "{completed} من {total} خطوة مكتملة",
    "noPresetsAvailable": "لا توجد نماذج متاحة. ارفع مكتبة نماذج للبدء.",
    "noActiveJourneys": "لا توجد مسارات نشطة بعد. طبّق قالباً للبدء.",
    "startStepTooltip": "ابدأ العمل على هذه الخطوة",
    "markAsDoneTooltip": "تحديد هذه الخطوة كمكتملة",
    "markAsSkippedTooltip": "تخطي هذه الخطوة",
    "resetStepTooltip": "إعادة تعيين هذه الخطوة إلى 'لم تبدأ'",
    "rename": "إعادة التسمية",
    "goToStep": "الانتقال إلى",
    "journeyProgress": "تقدم المسار",
    "upgradeAvailable": "يتوفر ترقية",
    "upgradeJourney": "ترقية المسار",
    "journeyUpgraded": "تم ترقية المسار بنجاح",
    "alreadyUpToDate": "محدَّث بالفعل",
    "journeyNotFound": "لم يُعثر على المسار.",
    "stats": "الإحصاءات",
    "noMatchingPresets": "لا توجد قوالب تطابق هذا الفلتر.",
    "createUnderlyingObjects": "إنشاء الكائنات الأساسية",
    "createUnderlyingObjectsHelp": "عند إلغاء التحديد، يُنشأ المسار كقائمة مراجعة بحتة دون إنشاء تقييمات أو أصول أو كائنات أخرى تلقائياً.",
    "doneEditing": "انتهاء التعديل",
    "noLinkedObject": "— لا يوجد كائن مرتبط —",
    "hideDescriptions": "إخفاء الأوصاف",
}

fixed = 0
for key, arabic in DIRECT.items():
    if key in ar and ar[key] == en.get(key, ar[key]):
        ar[key] = arabic
        fixed += 1

print(f"Fourth-pass direct: fixed {fixed} keys")

# ── Pattern-based pass on remaining ─────────────────────────────────────────
STILL_EN = [(k, en[k]) for k in ar
            if k in en and isinstance(en[k], str)
            and ar[k] == en[k] and not k.startswith("$")]

PATTERNS = [
    (r"^add([A-Z])", lambda m: "إضافة " + m.group(1)),
    (r"^change([A-Z])", lambda m: "تغيير " + m.group(1)),
    (r"^delete([A-Z])", lambda m: "حذف " + m.group(1)),
    (r"^view([A-Z])", lambda m: "عرض " + m.group(1)),
    (r"^create([A-Z])", lambda m: "إنشاء " + m.group(1)),
    (r"^edit([A-Z])", lambda m: "تعديل " + m.group(1)),
    (r"^remove([A-Z])", lambda m: "إزالة " + m.group(1)),
    (r"^update([A-Z])", lambda m: "تحديث " + m.group(1)),
    (r"^select([A-Z])", lambda m: "اختيار " + m.group(1)),
    (r"^manage([A-Z])", lambda m: "إدارة " + m.group(1)),
    (r"^export([A-Z])", lambda m: "تصدير " + m.group(1)),
    (r"^import([A-Z])", lambda m: "استيراد " + m.group(1)),
    (r"^configure([A-Z])", lambda m: "تهيئة " + m.group(1)),
    (r"^upload([A-Z])", lambda m: "رفع " + m.group(1)),
    (r"^download([A-Z])", lambda m: "تنزيل " + m.group(1)),
    (r"^search([A-Z])", lambda m: "البحث عن " + m.group(1)),
    (r"^filter([A-Z])", lambda m: "تصفية " + m.group(1)),
    (r"^show([A-Z])", lambda m: "عرض " + m.group(1)),
    (r"^hide([A-Z])", lambda m: "إخفاء " + m.group(1)),
    (r"^reset([A-Z])", lambda m: "إعادة تعيين " + m.group(1)),
    (r"^confirm([A-Z])", lambda m: "تأكيد " + m.group(1)),
    (r"^cancel([A-Z])", lambda m: "إلغاء " + m.group(1)),
    (r"^submit([A-Z])", lambda m: "إرسال " + m.group(1)),
    (r"^save([A-Z])", lambda m: "حفظ " + m.group(1)),
    (r"^load([A-Z])", lambda m: "تحميل " + m.group(1)),
    (r"^send([A-Z])", lambda m: "إرسال " + m.group(1)),
    (r"^open([A-Z])", lambda m: "فتح " + m.group(1)),
    (r"^close([A-Z])", lambda m: "إغلاق " + m.group(1)),
    (r"^enable([A-Z])", lambda m: "تمكين " + m.group(1)),
    (r"^disable([A-Z])", lambda m: "تعطيل " + m.group(1)),
    (r"Description$", lambda m: "الوصف"),
    (r"HelpText$", lambda m: "نص المساعدة"),
]

import re as _re

pattern_fixed = 0
for key, _ in STILL_EN:
    for pat, fn in PATTERNS:
        m = _re.search(pat, key)
        if m:
            # Only if English value looks short / actionable
            en_val = en.get(key, "")
            if len(en_val) < 120:
                ar[key] = fn(m)
                pattern_fixed += 1
            break

print(f"Fourth-pass pattern: fixed {pattern_fixed} additional keys")

still = [(k, en[k]) for k in ar if k in en and isinstance(en[k], str) and ar[k] == en[k] and not k.startswith("$")]
print(f"Still in English: {len(still)}")

with open(DST, "w", encoding="utf-8") as f:
    json.dump(ar, f, ensure_ascii=False, indent=2)

print(f"Written to {DST}")
