from enum import IntEnum, StrEnum


class DecisionStatus(StrEnum):
    CANDIDATE = "CANDIDATE"
    DEFERRED = "DEFERRED"
    BLOCKED = "BLOCKED"
    HUMAN_REVIEW_REQUIRED = "HUMAN_REVIEW_REQUIRED"
    ALLOWED = "ALLOWED"


class EvidenceRank(IntEnum):
    ZERO = 0
    CANDIDATE = 1
    HYPOTHESIS = 2
    SUPPORTED = 3
    VERIFIED = 4


class FailedStage(StrEnum):
    ORIGIN = "ORIGIN"
    BRANCH_LICENSE = "BRANCH_LICENSE"
    EFFECTIVE_ATTRIBUTE = "EFFECTIVE_ATTRIBUTE"
    SABAB = "SABAB"
    CONDITIONS = "CONDITIONS"
    MANI = "MANI"
    QADIH_DIFFERENCE = "QADIH_DIFFERENCE"
    EVIDENCE_TRACE = "EVIDENCE_TRACE"
    RANK = "RANK"
    RESIDUALS = "RESIDUALS"
    HANDOFF = "HANDOFF"
    CONDITION = "CONDITIONS"
    QADIH = "QADIH_DIFFERENCE"
    EVIDENCE = "EVIDENCE_TRACE"
    ACTION = "HANDOFF"
