# Generated by Django 6.0.3 on 2026-06-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0023_registrationrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='tier',
            field=models.PositiveSmallIntegerField(default=5, help_text='Privilege tier: 1 = System Administrator (highest), 7 = Third-Party Respondent (lowest). Lower number means more privileged.', verbose_name='privilege tier'),
        ),
    ]
