#!/bin/bash

# Configure application URLs for GitHub Codespaces or local development
# This script runs on every container start (postStartCommand)

# Detect workspace root dynamically (works in Codespaces and local containers)
WORKSPACE_DIR="$(git -C "$(dirname "$0")" rev-parse --show-toplevel 2>/dev/null || echo "/workspaces/sanadcom")"
FRONTEND_ENV_FILE="${WORKSPACE_DIR}/src/frontend/.env.local"

echo "🔗 Configuring application URLs..."

if [ -n "${CODESPACE_NAME}" ] && [ -n "${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}" ]; then
  # Running in GitHub Codespaces – build URLs from Codespace env vars
  BACKEND_URL="https://${CODESPACE_NAME}-8000.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}"
  FRONTEND_URL="https://${CODESPACE_NAME}-5000.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}"

  echo "📍 Detected GitHub Codespaces environment"
  echo "   Frontend URL : ${FRONTEND_URL}"
  echo "   Backend URL  : ${BACKEND_URL}"

  # Write frontend environment file
  cat > "${FRONTEND_ENV_FILE}" <<EOF
# Auto-generated by .devcontainer/configure-urls.sh – do not edit manually
NEXT_PUBLIC_API_URL=${BACKEND_URL}
EOF

  # Update backend CORS_ORIGINS to allow the Codespace frontend origin
  BACKEND_ENV_FILE="${WORKSPACE_DIR}/src/backend/.env"
  if [ -f "${BACKEND_ENV_FILE}" ]; then
    # Update existing CORS_ORIGINS line if present, otherwise append
    if grep -q "^CORS_ORIGINS=" "${BACKEND_ENV_FILE}"; then
      sed -i "s|^CORS_ORIGINS=.*|CORS_ORIGINS=http://localhost:5000,http://localhost:8000,${FRONTEND_URL}|" "${BACKEND_ENV_FILE}"
    else
      echo "CORS_ORIGINS=http://localhost:5000,http://localhost:8000,${FRONTEND_URL}" >> "${BACKEND_ENV_FILE}"
    fi
  fi

  echo "✅ Codespaces URL configuration complete"
else
  # Running locally – use localhost defaults
  echo "📍 Detected local development environment"

  cat > "${FRONTEND_ENV_FILE}" <<EOF
# Auto-generated by .devcontainer/configure-urls.sh – do not edit manually
NEXT_PUBLIC_API_URL=http://localhost:8000
EOF

  echo "✅ Local URL configuration complete"
fi

echo ""
echo "💡 Frontend env written to: ${FRONTEND_ENV_FILE}"
