from enum import Enum, IntEnum


class EngineType(str, Enum):
    LLM = "LLM"
    INDUCTION = "INDUCTION"
    QIYAS = "QIYAS"
    MATHEMATICAL_PROVER = "MATHEMATICAL_PROVER"
    LINGUISTIC_ANALYZER = "LINGUISTIC_ANALYZER"
    CAUSAL_ENGINE = "CAUSAL_ENGINE"
    RULE_ENGINE = "RULE_ENGINE"
    HUMAN = "HUMAN"
    OTHER = "OTHER"


class RelationType(str, Enum):
    IDENTITY = "IDENTITY"
    EQUALITY = "EQUALITY"
    PREDICATION = "PREDICATION"
    INCLUSION = "INCLUSION"
    PART_WHOLE = "PART_WHOLE"
    TEMPORAL = "TEMPORAL"
    SPATIAL = "SPATIAL"
    CAUSAL = "CAUSAL"
    CONDITIONAL = "CONDITIONAL"
    CORRELATIONAL = "CORRELATIONAL"
    QUANTITATIVE = "QUANTITATIVE"
    DEPENDENCY = "DEPENDENCY"
    REFERENCE = "REFERENCE"
    TRANSFORMATION = "TRANSFORMATION"
    GOVERNANCE_APPLICABILITY = "GOVERNANCE_APPLICABILITY"
    LINGUISTIC_ISNAD = "LINGUISTIC_ISNAD"
    CUSTOM = "CUSTOM"


class ProtocolStage(str, Enum):
    UNIT = "UNIT"
    IDENTITY = "IDENTITY"
    DOMAIN = "DOMAIN"
    RELATION = "RELATION"
    SCOPE = "SCOPE"
    CLOSURE = "CLOSURE"
    CERTIFICATION = "CERTIFICATION"


class TransitionStatus(str, Enum):
    CERTIFIED = "CERTIFIED"
    SUSPENDED = "SUSPENDED"
    BLOCKED = "BLOCKED"


class ConstitutionalRank(IntEnum):
    ZERO = 0
    CANDIDATE = 1
    PLAUSIBLE = 2
    SUPPORTED = 3
    CORROBORATED = 4
    VERIFIED = 5
    ASSURED = 6


class ResidualKind(str, Enum):
    SELF_CERTIFICATION = "SELF_CERTIFICATION"
    MISSING_UNIT_PROOF = "MISSING_UNIT_PROOF"
    IDENTITY_GAP = "IDENTITY_GAP"
    DOMAIN_MISMATCH = "DOMAIN_MISMATCH"
    RELATION_UNLICENSED = "RELATION_UNLICENSED"
    SCOPE_EXCEEDED = "SCOPE_EXCEEDED"
    MISSING_REFERENCE = "MISSING_REFERENCE"
    MISSING_EVIDENCE = "MISSING_EVIDENCE"
    ALTERNATIVE_UNCHECKED = "ALTERNATIVE_UNCHECKED"
    DEFEATER_ACTIVE = "DEFEATER_ACTIVE"
    INFERENCE_GAP = "INFERENCE_GAP"
    CONTRADICTION = "CONTRADICTION"
    VERSION_MISMATCH = "VERSION_MISMATCH"
