"""remove display_name columns from roles

Revision ID: 4ecec7f4ec4f
Revises: a6395fa43d4c
Create Date: 2026-02-26 11:03:20.040806+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4ecec7f4ec4f'
down_revision = 'a6395fa43d4c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_responses_assessment_id'), table_name='assessment_responses')
    op.drop_index(op.f('ix_assessment_responses_assessment_status'), table_name='assessment_responses')
    op.drop_index(op.f('ix_assessment_responses_control_id'), table_name='assessment_responses')
    op.drop_table('assessment_responses')
    op.drop_index(op.f('ix_assessment_status_history_assessment_id'), table_name='assessment_status_history')
    op.drop_index(op.f('ix_assessment_status_history_assessment_timestamp'), table_name='assessment_status_history')
    op.drop_index(op.f('ix_assessment_status_history_changed_at'), table_name='assessment_status_history')
    op.drop_index(op.f('ix_assessment_status_history_to_status'), table_name='assessment_status_history')
    op.drop_table('assessment_status_history')
    op.drop_index(op.f('ix_assessment_instances_assessment_id'), table_name='assessment_instances')
    op.drop_index(op.f('ix_assessment_instances_assessment_type'), table_name='assessment_instances')
    op.drop_index(op.f('ix_assessment_instances_assessor_status'), table_name='assessment_instances')
    op.drop_index(op.f('ix_assessment_instances_assigned_assessor_id'), table_name='assessment_instances')
    op.drop_index(op.f('ix_assessment_instances_due_date'), table_name='assessment_instances')
    op.drop_index(op.f('ix_assessment_instances_framework'), table_name='assessment_instances')
    op.drop_index(op.f('ix_assessment_instances_status'), table_name='assessment_instances')
    op.drop_index(op.f('ix_assessment_instances_status_framework'), table_name='assessment_instances')
    op.drop_table('assessment_instances')
    op.alter_column('ai_models', 'model_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('CLASSIFICATION', 'REGRESSION', 'NLP', 'COMPUTER_VISION', 'GENERATIVE', 'RECOMMENDATION', 'OTHER', name='modeltype', native_enum=False),
               existing_nullable=False)
    op.alter_column('ai_models', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('DEVELOPMENT', 'TESTING', 'STAGING', 'PRODUCTION', 'DEPRECATED', 'RETIRED', name='modelstatus', native_enum=False),
               existing_nullable=False)
    op.drop_index(op.f('ix_ai_models_model_type'), table_name='ai_models')
    op.drop_index(op.f('ix_ai_models_status'), table_name='ai_models')
    op.alter_column('asset_inventory', 'classification',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED', name='documentclassification', native_enum=False),
               existing_nullable=False)
    op.drop_index(op.f('ix_asset_inventory_asset_number'), table_name='asset_inventory')
    op.drop_index(op.f('ix_asset_inventory_asset_type'), table_name='asset_inventory')
    op.drop_index(op.f('ix_asset_inventory_classification'), table_name='asset_inventory')
    op.create_index(op.f('ix_asset_inventory_asset_id'), 'asset_inventory', ['asset_id'], unique=False)
    op.create_unique_constraint(None, 'asset_inventory', ['asset_number'])
    op.add_column('audit_engagements', sa.Column('objective_en', sa.Text(), nullable=False))
    op.add_column('audit_engagements', sa.Column('objective_ar', sa.Text(), nullable=False))
    op.add_column('audit_engagements', sa.Column('control_domain', sa.String(length=200), nullable=True))
    op.add_column('audit_engagements', sa.Column('controls_in_scope', sa.JSON(), nullable=False))
    op.add_column('audit_engagements', sa.Column('departments_in_scope', sa.JSON(), nullable=True))
    op.add_column('audit_engagements', sa.Column('systems_in_scope', sa.JSON(), nullable=True))
    op.add_column('audit_engagements', sa.Column('scheduled_date', sa.DateTime(), nullable=False))
    op.add_column('audit_engagements', sa.Column('scheduled_duration_hours', sa.Integer(), nullable=False))
    op.add_column('audit_engagements', sa.Column('actual_start_time', sa.DateTime(), nullable=True))
    op.add_column('audit_engagements', sa.Column('actual_end_time', sa.DateTime(), nullable=True))
    op.add_column('audit_engagements', sa.Column('auditor_ids', sa.JSON(), nullable=False))
    op.add_column('audit_engagements', sa.Column('auditee_ids', sa.JSON(), nullable=False))
    op.add_column('audit_engagements', sa.Column('agenda_en', sa.Text(), nullable=True))
    op.add_column('audit_engagements', sa.Column('agenda_ar', sa.Text(), nullable=True))
    op.add_column('audit_engagements', sa.Column('meeting_notes_en', sa.Text(), nullable=True))
    op.add_column('audit_engagements', sa.Column('meeting_notes_ar', sa.Text(), nullable=True))
    op.add_column('audit_engagements', sa.Column('completion_percentage', sa.Integer(), nullable=False))
    op.alter_column('audit_engagements', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PLANNED', 'IN_PREPARATION', 'IN_PROGRESS', 'PENDING_RESPONSE', 'UNDER_REVIEW', 'COMPLETED', 'CANCELLED', name='auditstatus', native_enum=False),
               existing_nullable=False)
    op.create_index(op.f('ix_audit_engagements_engagement_id'), 'audit_engagements', ['engagement_id'], unique=False)
    op.create_unique_constraint(None, 'audit_engagements', ['engagement_code'])
    op.drop_constraint(op.f('audit_engagements_lead_auditor_id_fkey'), 'audit_engagements', type_='foreignkey')
    op.drop_column('audit_engagements', 'lead_auditor_id')
    op.add_column('audit_evidence', sa.Column('title_en', sa.String(length=500), nullable=False))
    op.add_column('audit_evidence', sa.Column('title_ar', sa.String(length=500), nullable=False))
    op.add_column('audit_evidence', sa.Column('description_en', sa.Text(), nullable=True))
    op.add_column('audit_evidence', sa.Column('description_ar', sa.Text(), nullable=True))
    op.add_column('audit_evidence', sa.Column('control_id', sa.String(length=50), nullable=False))
    op.add_column('audit_evidence', sa.Column('control_requirement_en', sa.Text(), nullable=False))
    op.add_column('audit_evidence', sa.Column('control_requirement_ar', sa.Text(), nullable=False))
    op.add_column('audit_evidence', sa.Column('evidence_type', sa.String(length=100), nullable=False))
    op.add_column('audit_evidence', sa.Column('evidence_category', sa.String(length=100), nullable=False))
    op.add_column('audit_evidence', sa.Column('requested_date', sa.DateTime(), nullable=False))
    op.add_column('audit_evidence', sa.Column('due_date', sa.DateTime(), nullable=False))
    op.add_column('audit_evidence', sa.Column('submitted_date', sa.DateTime(), nullable=True))
    op.add_column('audit_evidence', sa.Column('file_path', sa.String(length=1000), nullable=True))
    op.add_column('audit_evidence', sa.Column('file_url', sa.String(length=1000), nullable=True))
    op.add_column('audit_evidence', sa.Column('file_hash', sa.String(length=128), nullable=True))
    op.add_column('audit_evidence', sa.Column('file_size_bytes', sa.Integer(), nullable=True))
    op.add_column('audit_evidence', sa.Column('reviewed_date', sa.DateTime(), nullable=True))
    op.add_column('audit_evidence', sa.Column('reviewer_notes_en', sa.Text(), nullable=True))
    op.add_column('audit_evidence', sa.Column('reviewer_notes_ar', sa.Text(), nullable=True))
    op.add_column('audit_evidence', sa.Column('adequacy_rating', sa.Integer(), nullable=True))
    op.add_column('audit_evidence', sa.Column('completeness_score', sa.Integer(), nullable=True))
    op.add_column('audit_evidence', sa.Column('tags', sa.JSON(), nullable=True))
    op.alter_column('audit_evidence', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'COLLECTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', name='evidencestatus', native_enum=False),
               existing_nullable=False)
    op.create_index(op.f('ix_audit_evidence_evidence_id'), 'audit_evidence', ['evidence_id'], unique=False)
    op.create_unique_constraint(None, 'audit_evidence', ['evidence_reference'])
    op.add_column('audit_findings', sa.Column('description_en', sa.Text(), nullable=False))
    op.add_column('audit_findings', sa.Column('description_ar', sa.Text(), nullable=False))
    op.add_column('audit_findings', sa.Column('evidence_reference_en', sa.Text(), nullable=False))
    op.add_column('audit_findings', sa.Column('evidence_reference_ar', sa.Text(), nullable=False))
    op.add_column('audit_findings', sa.Column('finding_type', sa.String(length=100), nullable=False))
    op.add_column('audit_findings', sa.Column('control_reference', sa.String(length=50), nullable=False))
    op.add_column('audit_findings', sa.Column('control_requirement_en', sa.Text(), nullable=False))
    op.add_column('audit_findings', sa.Column('control_requirement_ar', sa.Text(), nullable=False))
    op.add_column('audit_findings', sa.Column('gap_identified_en', sa.Text(), nullable=False))
    op.add_column('audit_findings', sa.Column('gap_identified_ar', sa.Text(), nullable=False))
    op.add_column('audit_findings', sa.Column('iso27001_clause', sa.String(length=50), nullable=True))
    op.add_column('audit_findings', sa.Column('nca_ecc_control', sa.String(length=50), nullable=True))
    op.add_column('audit_findings', sa.Column('nca_ccc_control', sa.String(length=50), nullable=True))
    op.add_column('audit_findings', sa.Column('pdpl_article', sa.String(length=50), nullable=True))
    op.add_column('audit_findings', sa.Column('risk_rating', sa.String(length=50), nullable=False))
    op.add_column('audit_findings', sa.Column('impact_description_en', sa.Text(), nullable=True))
    op.add_column('audit_findings', sa.Column('impact_description_ar', sa.Text(), nullable=True))
    op.add_column('audit_findings', sa.Column('recommendation_en', sa.Text(), nullable=False))
    op.add_column('audit_findings', sa.Column('recommendation_ar', sa.Text(), nullable=False))
    op.add_column('audit_findings', sa.Column('due_date', sa.DateTime(), nullable=False))
    op.add_column('audit_findings', sa.Column('corrective_action_plan_en', sa.Text(), nullable=True))
    op.add_column('audit_findings', sa.Column('corrective_action_plan_ar', sa.Text(), nullable=True))
    op.add_column('audit_findings', sa.Column('target_closure_date', sa.DateTime(), nullable=True))
    op.add_column('audit_findings', sa.Column('actual_closure_date', sa.DateTime(), nullable=True))
    op.add_column('audit_findings', sa.Column('progress_percentage', sa.Integer(), nullable=False))
    op.add_column('audit_findings', sa.Column('verification_evidence_en', sa.Text(), nullable=True))
    op.add_column('audit_findings', sa.Column('verification_evidence_ar', sa.Text(), nullable=True))
    op.add_column('audit_findings', sa.Column('verification_date', sa.DateTime(), nullable=True))
    op.add_column('audit_findings', sa.Column('verification_notes_en', sa.Text(), nullable=True))
    op.add_column('audit_findings', sa.Column('verification_notes_ar', sa.Text(), nullable=True))
    op.add_column('audit_findings', sa.Column('escalated', sa.Boolean(), nullable=False))
    op.add_column('audit_findings', sa.Column('escalation_reason_en', sa.Text(), nullable=True))
    op.add_column('audit_findings', sa.Column('escalation_reason_ar', sa.Text(), nullable=True))
    op.add_column('audit_findings', sa.Column('escalation_date', sa.DateTime(), nullable=True))
    op.add_column('audit_findings', sa.Column('identified_date', sa.DateTime(), nullable=False))
    op.alter_column('audit_findings', 'severity',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'OBSERVATION', 'OPPORTUNITY_FOR_IMPROVEMENT', name='findingseverity', native_enum=False),
               existing_nullable=False)
    op.alter_column('audit_findings', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('OPEN', 'IN_PROGRESS', 'PENDING_VERIFICATION', 'VERIFIED', 'CLOSED', 'RISK_ACCEPTED', name='findingstatus', native_enum=False),
               existing_nullable=False)
    op.create_index(op.f('ix_audit_findings_finding_id'), 'audit_findings', ['finding_id'], unique=False)
    op.create_unique_constraint(None, 'audit_findings', ['finding_number'])
    op.alter_column('audit_logs', 'resource',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
    op.drop_index(op.f('idx_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_user_action'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_column('audit_logs', 'resource_id')
    op.drop_column('audit_logs', 'ip_address')
    op.drop_column('audit_logs', 'user_agent')
    op.drop_column('audit_logs', 'status')
    op.drop_column('audit_logs', 'timestamp')
    op.alter_column('backup_jobs', 'backup_type',
               existing_type=postgresql.ENUM('full', 'incremental', 'differential', name='backuptype'),
               type_=sa.Enum('FULL', 'INCREMENTAL', 'DIFFERENTIAL', name='backuptype', native_enum=False),
               existing_nullable=False)
    op.alter_column('backup_jobs', 'status',
               existing_type=postgresql.ENUM('pending', 'in_progress', 'completed', 'failed', 'archived', name='backupstatus'),
               type_=sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'ARCHIVED', name='backupstatus', native_enum=False),
               existing_nullable=False)
    op.drop_index(op.f('ix_backup_jobs_created_at'), table_name='backup_jobs')
    op.drop_index(op.f('ix_backup_jobs_status'), table_name='backup_jobs')
    op.drop_index(op.f('ix_bias_tests_model_id'), table_name='bias_test_results')
    op.drop_index(op.f('ix_bias_tests_severity'), table_name='bias_test_results')
    op.alter_column('controls', 'framework',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('controls', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_index(op.f('ix_controls_framework_version'), table_name='controls')
    op.drop_index(op.f('ix_controls_source_pdf'), table_name='controls')
    op.drop_index(op.f('ix_controls_subdomain'), table_name='controls')
    op.create_index(op.f('ix_controls_domain'), 'controls', ['domain'], unique=False)
    op.create_index(op.f('ix_controls_status'), 'controls', ['status'], unique=False)
    op.drop_column('controls', 'framework_version')
    op.drop_column('controls', 'source_pdf')
    op.drop_column('controls', 'mapping_pdpl')
    op.drop_column('controls', 'mapping_ecc')
    op.drop_column('controls', 'mapping_dcc')
    op.drop_column('controls', 'control_clause_en')
    op.drop_column('controls', 'mapping_ccc')
    op.drop_column('controls', 'evidence_examples')
    op.drop_column('controls', 'control_clause_ar')
    op.drop_column('controls', 'source_page')
    op.drop_column('controls', 'subdomain')
    op.add_column('corrective_actions', sa.Column('description_en', sa.Text(), nullable=False))
    op.add_column('corrective_actions', sa.Column('description_ar', sa.Text(), nullable=False))
    op.add_column('corrective_actions', sa.Column('root_cause_en', sa.Text(), nullable=False))
    op.add_column('corrective_actions', sa.Column('root_cause_ar', sa.Text(), nullable=False))
    op.add_column('corrective_actions', sa.Column('root_cause_category', sa.String(length=100), nullable=True))
    op.add_column('corrective_actions', sa.Column('action_steps_en', sa.JSON(), nullable=False))
    op.add_column('corrective_actions', sa.Column('action_steps_ar', sa.JSON(), nullable=False))
    op.add_column('corrective_actions', sa.Column('assigned_to_ids', sa.JSON(), nullable=True))
    op.add_column('corrective_actions', sa.Column('planned_start_date', sa.DateTime(), nullable=False))
    op.add_column('corrective_actions', sa.Column('planned_completion_date', sa.DateTime(), nullable=False))
    op.add_column('corrective_actions', sa.Column('actual_start_date', sa.DateTime(), nullable=True))
    op.add_column('corrective_actions', sa.Column('actual_completion_date', sa.DateTime(), nullable=True))
    op.add_column('corrective_actions', sa.Column('progress_percentage', sa.Integer(), nullable=False))
    op.add_column('corrective_actions', sa.Column('effectiveness_verified', sa.Boolean(), nullable=False))
    op.add_column('corrective_actions', sa.Column('verification_method_en', sa.Text(), nullable=True))
    op.add_column('corrective_actions', sa.Column('verification_method_ar', sa.Text(), nullable=True))
    op.add_column('corrective_actions', sa.Column('verification_date', sa.DateTime(), nullable=True))
    op.add_column('corrective_actions', sa.Column('last_update_en', sa.Text(), nullable=True))
    op.add_column('corrective_actions', sa.Column('last_update_ar', sa.Text(), nullable=True))
    op.create_index(op.f('ix_corrective_actions_action_id'), 'corrective_actions', ['action_id'], unique=False)
    op.create_unique_constraint(None, 'corrective_actions', ['action_number'])
    op.drop_index(op.f('ix_dr_plans_active'), table_name='disaster_recovery_plans')
    op.drop_index(op.f('ix_dr_plans_approved'), table_name='disaster_recovery_plans')
    op.drop_index(op.f('ix_dr_plans_version'), table_name='disaster_recovery_plans')
    op.drop_index(op.f('ix_doc_versions_policy_id'), table_name='document_versions')
    op.create_index(op.f('ix_document_versions_version_id'), 'document_versions', ['version_id'], unique=False)
    op.alter_column('evidence', 'evidence_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('POLICY', 'PROCEDURE', 'LOG', 'SCREENSHOT', 'REPORT', 'CERTIFICATE', 'OTHER', name='evidencetype', native_enum=False),
               existing_nullable=False)
    op.alter_column('evidence', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PENDING', 'COLLECTED', 'VALIDATED', 'REJECTED', 'EXPIRED', name='evidencestatus', native_enum=False),
               existing_nullable=True)
    op.create_index(op.f('ix_evidence_control_id'), 'evidence', ['control_id'], unique=False)
    op.create_index(op.f('ix_evidence_status'), 'evidence', ['status'], unique=False)
    op.alter_column('isms_policies', 'policy_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('INFORMATION_SECURITY', 'ACCESS_CONTROL', 'ASSET_MANAGEMENT', 'CRYPTOGRAPHY', 'PHYSICAL_SECURITY', 'OPERATIONS_SECURITY', 'COMMUNICATIONS_SECURITY', 'SYSTEM_ACQUISITION', 'SUPPLIER_RELATIONSHIPS', 'INCIDENT_MANAGEMENT', 'BUSINESS_CONTINUITY', 'COMPLIANCE', 'PRIVACY', 'CLOUD_SECURITY', 'AI_GOVERNANCE', name='policytype', native_enum=False),
               existing_nullable=False)
    op.alter_column('isms_policies', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('DRAFT', 'UNDER_REVIEW', 'APPROVED', 'PUBLISHED', 'REVISION_REQUIRED', 'ARCHIVED', name='policystatus', native_enum=False),
               existing_nullable=False)
    op.alter_column('isms_policies', 'classification',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED', name='documentclassification', native_enum=False),
               existing_nullable=False)
    op.drop_index(op.f('ix_isms_policies_policy_number'), table_name='isms_policies')
    op.drop_index(op.f('ix_isms_policies_policy_type'), table_name='isms_policies')
    op.drop_index(op.f('ix_isms_policies_status'), table_name='isms_policies')
    op.create_unique_constraint(None, 'isms_policies', ['policy_number'])
    op.drop_index(op.f('ix_model_audits_model_id'), table_name='model_audits')
    op.alter_column('permissions', 'action',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_column('permissions', 'created_at')
    op.drop_index(op.f('ix_policy_acks_policy_id'), table_name='policy_acknowledgements')
    op.drop_index(op.f('ix_policy_acks_user_id'), table_name='policy_acknowledgements')
    op.create_index(op.f('ix_policy_acknowledgements_acknowledgement_id'), 'policy_acknowledgements', ['acknowledgement_id'], unique=False)
    op.drop_index(op.f('ix_policy_exceptions_exception_number'), table_name='policy_exceptions')
    op.drop_index(op.f('ix_policy_exceptions_status'), table_name='policy_exceptions')
    op.create_index(op.f('ix_policy_exceptions_exception_id'), 'policy_exceptions', ['exception_id'], unique=False)
    op.create_unique_constraint(None, 'policy_exceptions', ['exception_number'])
    op.alter_column('recovery_tests', 'status',
               existing_type=postgresql.ENUM('scheduled', 'in_progress', 'successful', 'failed', name='recoverystatus'),
               type_=sa.Enum('SCHEDULED', 'IN_PROGRESS', 'SUCCESSFUL', 'FAILED', name='recoverystatus', native_enum=False),
               existing_nullable=False)
    op.drop_index(op.f('ix_recovery_tests_backup_job_id'), table_name='recovery_tests')
    op.drop_index(op.f('ix_recovery_tests_scheduled_date'), table_name='recovery_tests')
    op.drop_index(op.f('ix_recovery_tests_status'), table_name='recovery_tests')
    op.add_column('refresh_tokens', sa.Column('revoked_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_column('refresh_tokens', 'is_revoked')
    op.alter_column('reports', 'report_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('COMPLIANCE_SUMMARY', 'CONTROL_POSTURE', 'EVIDENCE_STATUS', 'RISK_HEATMAP', 'AUDIT_READINESS', 'EXECUTIVE_DASHBOARD', name='reporttype', native_enum=False),
               existing_nullable=False)
    op.alter_column('reports', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PENDING', 'GENERATING', 'COMPLETED', 'FAILED', name='reportstatus', native_enum=False),
               existing_nullable=True)
    op.drop_column('roles', 'updated_at')
    op.drop_column('roles', 'is_system')
    op.alter_column('security_events', 'event_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('AUTHENTICATION_FAILURE', 'AUTHORIZATION_VIOLATION', 'DATA_ACCESS', 'DATA_MODIFICATION', 'SUSPICIOUS_ACTIVITY', 'MALWARE_DETECTED', 'VULNERABILITY_EXPLOITED', 'POLICY_VIOLATION', 'SYSTEM_ALERT', name='securityeventtype', native_enum=False),
               existing_nullable=False)
    op.alter_column('security_events', 'severity',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFORMATIONAL', name='securityeventseverity', native_enum=False),
               existing_nullable=False)
    op.drop_index(op.f('ix_security_events_severity'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_timestamp'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_type'), table_name='security_events')
    op.create_index(op.f('ix_security_events_event_timestamp'), 'security_events', ['event_timestamp'], unique=False)
    op.create_foreign_key(None, 'security_events', 'security_incidents', ['incident_id'], ['incident_id'])
    op.add_column('security_incidents', sa.Column('category', sa.Enum('UNAUTHORIZED_ACCESS', 'MALWARE', 'PHISHING', 'DOS_DDOS', 'DATA_BREACH', 'INSIDER_THREAT', 'POLICY_VIOLATION', 'SYSTEM_FAILURE', 'OTHER', name='incidentcategory', native_enum=False), nullable=False))
    op.add_column('security_incidents', sa.Column('contained_at', sa.DateTime(), nullable=True))
    op.add_column('security_incidents', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.add_column('security_incidents', sa.Column('business_impact_en', sa.Text(), nullable=True))
    op.add_column('security_incidents', sa.Column('business_impact_ar', sa.Text(), nullable=True))
    op.add_column('security_incidents', sa.Column('financial_impact', sa.Integer(), nullable=True))
    op.add_column('security_incidents', sa.Column('immediate_actions_en', sa.Text(), nullable=True))
    op.add_column('security_incidents', sa.Column('immediate_actions_ar', sa.Text(), nullable=True))
    op.add_column('security_incidents', sa.Column('containment_actions_en', sa.Text(), nullable=True))
    op.add_column('security_incidents', sa.Column('containment_actions_ar', sa.Text(), nullable=True))
    op.add_column('security_incidents', sa.Column('eradication_actions_en', sa.Text(), nullable=True))
    op.add_column('security_incidents', sa.Column('eradication_actions_ar', sa.Text(), nullable=True))
    op.add_column('security_incidents', sa.Column('recovery_actions_en', sa.Text(), nullable=True))
    op.add_column('security_incidents', sa.Column('recovery_actions_ar', sa.Text(), nullable=True))
    op.add_column('security_incidents', sa.Column('nca_reported', sa.Boolean(), nullable=True))
    op.add_column('security_incidents', sa.Column('nca_reported_at', sa.DateTime(), nullable=True))
    op.add_column('security_incidents', sa.Column('sdaia_reported', sa.Boolean(), nullable=True))
    op.add_column('security_incidents', sa.Column('sdaia_reported_at', sa.DateTime(), nullable=True))
    op.add_column('security_incidents', sa.Column('reported_by', sa.Uuid(), nullable=False))
    op.add_column('security_incidents', sa.Column('incident_commander', sa.Uuid(), nullable=True))
    op.alter_column('security_incidents', 'severity',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='incidentseverity', native_enum=False),
               existing_nullable=False)
    op.alter_column('security_incidents', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('NEW', 'INVESTIGATING', 'CONTAINED', 'ERADICATED', 'RECOVERED', 'CLOSED', name='incidentstatus', native_enum=False),
               existing_nullable=False)
    op.drop_index(op.f('ix_security_incidents_number'), table_name='security_incidents')
    op.drop_index(op.f('ix_security_incidents_severity'), table_name='security_incidents')
    op.drop_index(op.f('ix_security_incidents_status'), table_name='security_incidents')
    op.create_foreign_key(None, 'security_incidents', 'users', ['incident_commander'], ['user_id'])
    op.create_foreign_key(None, 'security_incidents', 'users', ['reported_by'], ['user_id'])
    op.drop_column('security_incidents', 'eradication_actions')
    op.drop_column('security_incidents', 'estimated_impact_usd')
    op.drop_column('security_incidents', 'eradication_at')
    op.drop_column('security_incidents', 'regulatory_notification_deadline')
    op.drop_column('security_incidents', 'violated_controls')
    op.drop_column('security_incidents', 'data_types_compromised')
    op.drop_column('security_incidents', 'recovery_actions')
    op.drop_column('security_incidents', 'data_compromised')
    op.drop_column('security_incidents', 'containment_at')
    op.drop_column('security_incidents', 'created_at')
    op.drop_column('security_incidents', 'incident_type')
    op.drop_column('security_incidents', 'containment_actions')
    op.drop_column('security_incidents', 'updated_at')
    op.drop_column('security_incidents', 'attack_vector_en')
    op.drop_column('security_incidents', 'regulatory_notification_required')
    op.drop_column('security_incidents', 'attack_vector_ar')
    op.drop_column('security_incidents', 'recovery_at')
    op.drop_column('security_incidents', 'compliance_violations')
    op.drop_column('security_incidents', 'investigation_notes')
    op.drop_index(op.f('idx_users_email'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.add_column('security_incidents', sa.Column('investigation_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('security_incidents', sa.Column('compliance_violations', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('security_incidents', sa.Column('recovery_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('security_incidents', sa.Column('attack_vector_ar', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('security_incidents', sa.Column('regulatory_notification_required', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('security_incidents', sa.Column('attack_vector_en', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('security_incidents', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('security_incidents', sa.Column('containment_actions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('security_incidents', sa.Column('incident_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('security_incidents', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('security_incidents', sa.Column('containment_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('security_incidents', sa.Column('data_compromised', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('security_incidents', sa.Column('recovery_actions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('security_incidents', sa.Column('data_types_compromised', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('security_incidents', sa.Column('violated_controls', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('security_incidents', sa.Column('regulatory_notification_deadline', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('security_incidents', sa.Column('eradication_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('security_incidents', sa.Column('estimated_impact_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('security_incidents', sa.Column('eradication_actions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'security_incidents', type_='foreignkey')
    op.drop_constraint(None, 'security_incidents', type_='foreignkey')
    op.create_index(op.f('ix_security_incidents_status'), 'security_incidents', ['status'], unique=False)
    op.create_index(op.f('ix_security_incidents_severity'), 'security_incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_security_incidents_number'), 'security_incidents', ['incident_number'], unique=False)
    op.alter_column('security_incidents', 'status',
               existing_type=sa.Enum('NEW', 'INVESTIGATING', 'CONTAINED', 'ERADICATED', 'RECOVERED', 'CLOSED', name='incidentstatus', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('security_incidents', 'severity',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='incidentseverity', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('security_incidents', 'incident_commander')
    op.drop_column('security_incidents', 'reported_by')
    op.drop_column('security_incidents', 'sdaia_reported_at')
    op.drop_column('security_incidents', 'sdaia_reported')
    op.drop_column('security_incidents', 'nca_reported_at')
    op.drop_column('security_incidents', 'nca_reported')
    op.drop_column('security_incidents', 'recovery_actions_ar')
    op.drop_column('security_incidents', 'recovery_actions_en')
    op.drop_column('security_incidents', 'eradication_actions_ar')
    op.drop_column('security_incidents', 'eradication_actions_en')
    op.drop_column('security_incidents', 'containment_actions_ar')
    op.drop_column('security_incidents', 'containment_actions_en')
    op.drop_column('security_incidents', 'immediate_actions_ar')
    op.drop_column('security_incidents', 'immediate_actions_en')
    op.drop_column('security_incidents', 'financial_impact')
    op.drop_column('security_incidents', 'business_impact_ar')
    op.drop_column('security_incidents', 'business_impact_en')
    op.drop_column('security_incidents', 'resolved_at')
    op.drop_column('security_incidents', 'contained_at')
    op.drop_column('security_incidents', 'category')
    op.drop_constraint(None, 'security_events', type_='foreignkey')
    op.drop_index(op.f('ix_security_events_event_timestamp'), table_name='security_events')
    op.create_index(op.f('ix_security_events_type'), 'security_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_security_events_timestamp'), 'security_events', ['event_timestamp'], unique=False)
    op.create_index(op.f('ix_security_events_severity'), 'security_events', ['severity'], unique=False)
    op.alter_column('security_events', 'severity',
               existing_type=sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFORMATIONAL', name='securityeventseverity', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('security_events', 'event_type',
               existing_type=sa.Enum('AUTHENTICATION_FAILURE', 'AUTHORIZATION_VIOLATION', 'DATA_ACCESS', 'DATA_MODIFICATION', 'SUSPICIOUS_ACTIVITY', 'MALWARE_DETECTED', 'VULNERABILITY_EXPLOITED', 'POLICY_VIOLATION', 'SYSTEM_ALERT', name='securityeventtype', native_enum=False),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.add_column('roles', sa.Column('is_system', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('roles', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('reports', 'status',
               existing_type=sa.Enum('PENDING', 'GENERATING', 'COMPLETED', 'FAILED', name='reportstatus', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('reports', 'report_type',
               existing_type=sa.Enum('COMPLIANCE_SUMMARY', 'CONTROL_POSTURE', 'EVIDENCE_STATUS', 'RISK_HEATMAP', 'AUDIT_READINESS', 'EXECUTIVE_DASHBOARD', name='reporttype', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.add_column('refresh_tokens', sa.Column('is_revoked', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.drop_column('refresh_tokens', 'revoked_at')
    op.create_index(op.f('ix_recovery_tests_status'), 'recovery_tests', ['status'], unique=False)
    op.create_index(op.f('ix_recovery_tests_scheduled_date'), 'recovery_tests', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_recovery_tests_backup_job_id'), 'recovery_tests', ['backup_job_id'], unique=False)
    op.alter_column('recovery_tests', 'status',
               existing_type=sa.Enum('SCHEDULED', 'IN_PROGRESS', 'SUCCESSFUL', 'FAILED', name='recoverystatus', native_enum=False),
               type_=postgresql.ENUM('scheduled', 'in_progress', 'successful', 'failed', name='recoverystatus'),
               existing_nullable=False)
    op.drop_constraint(None, 'policy_exceptions', type_='unique')
    op.drop_index(op.f('ix_policy_exceptions_exception_id'), table_name='policy_exceptions')
    op.create_index(op.f('ix_policy_exceptions_status'), 'policy_exceptions', ['status'], unique=False)
    op.create_index(op.f('ix_policy_exceptions_exception_number'), 'policy_exceptions', ['exception_number'], unique=True)
    op.drop_index(op.f('ix_policy_acknowledgements_acknowledgement_id'), table_name='policy_acknowledgements')
    op.create_index(op.f('ix_policy_acks_user_id'), 'policy_acknowledgements', ['user_id'], unique=False)
    op.create_index(op.f('ix_policy_acks_policy_id'), 'policy_acknowledgements', ['policy_id'], unique=False)
    op.add_column('permissions', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('permissions', 'action',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.create_index(op.f('ix_model_audits_model_id'), 'model_audits', ['model_id'], unique=False)
    op.drop_constraint(None, 'isms_policies', type_='unique')
    op.create_index(op.f('ix_isms_policies_status'), 'isms_policies', ['status'], unique=False)
    op.create_index(op.f('ix_isms_policies_policy_type'), 'isms_policies', ['policy_type'], unique=False)
    op.create_index(op.f('ix_isms_policies_policy_number'), 'isms_policies', ['policy_number'], unique=True)
    op.alter_column('isms_policies', 'classification',
               existing_type=sa.Enum('PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED', name='documentclassification', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('isms_policies', 'status',
               existing_type=sa.Enum('DRAFT', 'UNDER_REVIEW', 'APPROVED', 'PUBLISHED', 'REVISION_REQUIRED', 'ARCHIVED', name='policystatus', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('isms_policies', 'policy_type',
               existing_type=sa.Enum('INFORMATION_SECURITY', 'ACCESS_CONTROL', 'ASSET_MANAGEMENT', 'CRYPTOGRAPHY', 'PHYSICAL_SECURITY', 'OPERATIONS_SECURITY', 'COMMUNICATIONS_SECURITY', 'SYSTEM_ACQUISITION', 'SUPPLIER_RELATIONSHIPS', 'INCIDENT_MANAGEMENT', 'BUSINESS_CONTINUITY', 'COMPLIANCE', 'PRIVACY', 'CLOUD_SECURITY', 'AI_GOVERNANCE', name='policytype', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_evidence_status'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_control_id'), table_name='evidence')
    op.alter_column('evidence', 'status',
               existing_type=sa.Enum('PENDING', 'COLLECTED', 'VALIDATED', 'REJECTED', 'EXPIRED', name='evidencestatus', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('evidence', 'evidence_type',
               existing_type=sa.Enum('POLICY', 'PROCEDURE', 'LOG', 'SCREENSHOT', 'REPORT', 'CERTIFICATE', 'OTHER', name='evidencetype', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_document_versions_version_id'), table_name='document_versions')
    op.create_index(op.f('ix_doc_versions_policy_id'), 'document_versions', ['policy_id'], unique=False)
    op.create_index(op.f('ix_dr_plans_version'), 'disaster_recovery_plans', ['version'], unique=False)
    op.create_index(op.f('ix_dr_plans_approved'), 'disaster_recovery_plans', ['approved'], unique=False)
    op.create_index(op.f('ix_dr_plans_active'), 'disaster_recovery_plans', ['active'], unique=False)
    op.drop_constraint(None, 'corrective_actions', type_='unique')
    op.drop_index(op.f('ix_corrective_actions_action_id'), table_name='corrective_actions')
    op.drop_column('corrective_actions', 'last_update_ar')
    op.drop_column('corrective_actions', 'last_update_en')
    op.drop_column('corrective_actions', 'verification_date')
    op.drop_column('corrective_actions', 'verification_method_ar')
    op.drop_column('corrective_actions', 'verification_method_en')
    op.drop_column('corrective_actions', 'effectiveness_verified')
    op.drop_column('corrective_actions', 'progress_percentage')
    op.drop_column('corrective_actions', 'actual_completion_date')
    op.drop_column('corrective_actions', 'actual_start_date')
    op.drop_column('corrective_actions', 'planned_completion_date')
    op.drop_column('corrective_actions', 'planned_start_date')
    op.drop_column('corrective_actions', 'assigned_to_ids')
    op.drop_column('corrective_actions', 'action_steps_ar')
    op.drop_column('corrective_actions', 'action_steps_en')
    op.drop_column('corrective_actions', 'root_cause_category')
    op.drop_column('corrective_actions', 'root_cause_ar')
    op.drop_column('corrective_actions', 'root_cause_en')
    op.drop_column('corrective_actions', 'description_ar')
    op.drop_column('corrective_actions', 'description_en')
    op.add_column('controls', sa.Column('subdomain', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.add_column('controls', sa.Column('source_page', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('controls', sa.Column('control_clause_ar', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('controls', sa.Column('evidence_examples', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('controls', sa.Column('mapping_ccc', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('controls', sa.Column('control_clause_en', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('controls', sa.Column('mapping_dcc', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('controls', sa.Column('mapping_ecc', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('controls', sa.Column('mapping_pdpl', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('controls', sa.Column('source_pdf', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('controls', sa.Column('framework_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_controls_status'), table_name='controls')
    op.drop_index(op.f('ix_controls_domain'), table_name='controls')
    op.create_index(op.f('ix_controls_subdomain'), 'controls', ['subdomain'], unique=False)
    op.create_index(op.f('ix_controls_source_pdf'), 'controls', ['source_pdf'], unique=False)
    op.create_index(op.f('ix_controls_framework_version'), 'controls', ['framework_version'], unique=False)
    op.alter_column('controls', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('controls', 'framework',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.create_index(op.f('ix_bias_tests_severity'), 'bias_test_results', ['severity'], unique=False)
    op.create_index(op.f('ix_bias_tests_model_id'), 'bias_test_results', ['model_id'], unique=False)
    op.create_index(op.f('ix_backup_jobs_status'), 'backup_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_backup_jobs_created_at'), 'backup_jobs', ['created_at'], unique=False)
    op.alter_column('backup_jobs', 'status',
               existing_type=sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'ARCHIVED', name='backupstatus', native_enum=False),
               type_=postgresql.ENUM('pending', 'in_progress', 'completed', 'failed', 'archived', name='backupstatus'),
               existing_nullable=False)
    op.alter_column('backup_jobs', 'backup_type',
               existing_type=sa.Enum('FULL', 'INCREMENTAL', 'DIFFERENTIAL', name='backuptype', native_enum=False),
               type_=postgresql.ENUM('full', 'incremental', 'differential', name='backuptype'),
               existing_nullable=False)
    op.add_column('audit_logs', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('ip_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('resource_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource'), 'audit_logs', ['resource'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('idx_audit_logs_user_action'), 'audit_logs', ['user_id', 'action'], unique=False)
    op.create_index(op.f('idx_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.alter_column('audit_logs', 'resource',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint(None, 'audit_findings', type_='foreignkey')
    op.drop_constraint(None, 'audit_findings', type_='unique')
    op.drop_index(op.f('ix_audit_findings_finding_id'), table_name='audit_findings')
    op.alter_column('audit_findings', 'status',
               existing_type=sa.Enum('OPEN', 'IN_PROGRESS', 'PENDING_VERIFICATION', 'VERIFIED', 'CLOSED', 'RISK_ACCEPTED', name='findingstatus', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('audit_findings', 'severity',
               existing_type=sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'OBSERVATION', 'OPPORTUNITY_FOR_IMPROVEMENT', name='findingseverity', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('audit_findings', 'identified_date')
    op.drop_column('audit_findings', 'escalation_date')
    op.drop_column('audit_findings', 'escalation_reason_ar')
    op.drop_column('audit_findings', 'escalation_reason_en')
    op.drop_column('audit_findings', 'escalated')
    op.drop_column('audit_findings', 'verification_notes_ar')
    op.drop_column('audit_findings', 'verification_notes_en')
    op.drop_column('audit_findings', 'verification_date')
    op.drop_column('audit_findings', 'verification_evidence_ar')
    op.drop_column('audit_findings', 'verification_evidence_en')
    op.drop_column('audit_findings', 'progress_percentage')
    op.drop_column('audit_findings', 'actual_closure_date')
    op.drop_column('audit_findings', 'target_closure_date')
    op.drop_column('audit_findings', 'corrective_action_plan_ar')
    op.drop_column('audit_findings', 'corrective_action_plan_en')
    op.drop_column('audit_findings', 'due_date')
    op.drop_column('audit_findings', 'recommendation_ar')
    op.drop_column('audit_findings', 'recommendation_en')
    op.drop_column('audit_findings', 'impact_description_ar')
    op.drop_column('audit_findings', 'impact_description_en')
    op.drop_column('audit_findings', 'risk_rating')
    op.drop_column('audit_findings', 'pdpl_article')
    op.drop_column('audit_findings', 'nca_ccc_control')
    op.drop_column('audit_findings', 'nca_ecc_control')
    op.drop_column('audit_findings', 'iso27001_clause')
    op.drop_column('audit_findings', 'gap_identified_ar')
    op.drop_column('audit_findings', 'gap_identified_en')
    op.drop_column('audit_findings', 'control_requirement_ar')
    op.drop_column('audit_findings', 'control_requirement_en')
    op.drop_column('audit_findings', 'control_reference')
    op.drop_column('audit_findings', 'finding_type')
    op.drop_column('audit_findings', 'evidence_reference_ar')
    op.drop_column('audit_findings', 'evidence_reference_en')
    op.drop_column('audit_findings', 'description_ar')
    op.drop_column('audit_findings', 'description_en')
    op.drop_constraint(None, 'audit_evidence', type_='unique')
    op.drop_index(op.f('ix_audit_evidence_evidence_id'), table_name='audit_evidence')
    op.alter_column('audit_evidence', 'status',
               existing_type=sa.Enum('PENDING', 'COLLECTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', name='evidencestatus', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('audit_evidence', 'tags')
    op.drop_column('audit_evidence', 'completeness_score')
    op.drop_column('audit_evidence', 'adequacy_rating')
    op.drop_column('audit_evidence', 'reviewer_notes_ar')
    op.drop_column('audit_evidence', 'reviewer_notes_en')
    op.drop_column('audit_evidence', 'reviewed_date')
    op.drop_column('audit_evidence', 'file_size_bytes')
    op.drop_column('audit_evidence', 'file_hash')
    op.drop_column('audit_evidence', 'file_url')
    op.drop_column('audit_evidence', 'file_path')
    op.drop_column('audit_evidence', 'submitted_date')
    op.drop_column('audit_evidence', 'due_date')
    op.drop_column('audit_evidence', 'requested_date')
    op.drop_column('audit_evidence', 'evidence_category')
    op.drop_column('audit_evidence', 'evidence_type')
    op.drop_column('audit_evidence', 'control_requirement_ar')
    op.drop_column('audit_evidence', 'control_requirement_en')
    op.drop_column('audit_evidence', 'control_id')
    op.drop_column('audit_evidence', 'description_ar')
    op.drop_column('audit_evidence', 'description_en')
    op.drop_column('audit_evidence', 'title_ar')
    op.drop_column('audit_evidence', 'title_en')
    op.add_column('audit_engagements', sa.Column('lead_auditor_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('audit_engagements_lead_auditor_id_fkey'), 'audit_engagements', 'users', ['lead_auditor_id'], ['user_id'])
    op.drop_constraint(None, 'audit_engagements', type_='unique')
    op.drop_index(op.f('ix_audit_engagements_engagement_id'), table_name='audit_engagements')
    op.alter_column('audit_engagements', 'status',
               existing_type=sa.Enum('PLANNED', 'IN_PREPARATION', 'IN_PROGRESS', 'PENDING_RESPONSE', 'UNDER_REVIEW', 'COMPLETED', 'CANCELLED', name='auditstatus', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('audit_engagements', 'completion_percentage')
    op.drop_column('audit_engagements', 'meeting_notes_ar')
    op.drop_column('audit_engagements', 'meeting_notes_en')
    op.drop_column('audit_engagements', 'agenda_ar')
    op.drop_column('audit_engagements', 'agenda_en')
    op.drop_column('audit_engagements', 'auditee_ids')
    op.drop_column('audit_engagements', 'auditor_ids')
    op.drop_column('audit_engagements', 'actual_end_time')
    op.drop_column('audit_engagements', 'actual_start_time')
    op.drop_column('audit_engagements', 'scheduled_duration_hours')
    op.drop_column('audit_engagements', 'scheduled_date')
    op.drop_column('audit_engagements', 'systems_in_scope')
    op.drop_column('audit_engagements', 'departments_in_scope')
    op.drop_column('audit_engagements', 'controls_in_scope')
    op.drop_column('audit_engagements', 'control_domain')
    op.drop_column('audit_engagements', 'objective_ar')
    op.drop_column('audit_engagements', 'objective_en')
    op.drop_constraint(None, 'asset_inventory', type_='unique')
    op.drop_index(op.f('ix_asset_inventory_asset_id'), table_name='asset_inventory')
    op.create_index(op.f('ix_asset_inventory_classification'), 'asset_inventory', ['classification'], unique=False)
    op.create_index(op.f('ix_asset_inventory_asset_type'), 'asset_inventory', ['asset_type'], unique=False)
    op.create_index(op.f('ix_asset_inventory_asset_number'), 'asset_inventory', ['asset_number'], unique=True)
    op.alter_column('asset_inventory', 'classification',
               existing_type=sa.Enum('PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED', name='documentclassification', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.create_index(op.f('ix_ai_models_status'), 'ai_models', ['status'], unique=False)
    op.create_index(op.f('ix_ai_models_model_type'), 'ai_models', ['model_type'], unique=False)
    op.alter_column('ai_models', 'status',
               existing_type=sa.Enum('DEVELOPMENT', 'TESTING', 'STAGING', 'PRODUCTION', 'DEPRECATED', 'RETIRED', name='modelstatus', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('ai_models', 'model_type',
               existing_type=sa.Enum('CLASSIFICATION', 'REGRESSION', 'NLP', 'COMPUTER_VISION', 'GENERATIVE', 'RECOMMENDATION', 'OTHER', name='modeltype', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.create_table('assessment_instances',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('assessment_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name_en', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name_ar', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description_en', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description_ar', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('assessment_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('framework', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('control_scope', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('domain_scope', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('assigned_assessor_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('reviewer_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('approver_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('launched_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('approved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('closed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('total_controls', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('completed_controls', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('progress_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('compliance_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('weighted_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('compliant_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('non_compliant_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('partial_compliant_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('not_applicable_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('approval_required', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('approval_comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('submitted_to_regulator', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('regulator_submission_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('regulator_reference_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['users.user_id'], name=op.f('assessment_instances_approver_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_assessor_id'], ['users.user_id'], name=op.f('assessment_instances_assigned_assessor_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.user_id'], name=op.f('assessment_instances_created_by_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.user_id'], name=op.f('assessment_instances_reviewer_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('assessment_instances_pkey'))
    )
    op.create_index(op.f('ix_assessment_instances_status_framework'), 'assessment_instances', ['status', 'framework'], unique=False)
    op.create_index(op.f('ix_assessment_instances_status'), 'assessment_instances', ['status'], unique=False)
    op.create_index(op.f('ix_assessment_instances_framework'), 'assessment_instances', ['framework'], unique=False)
    op.create_index(op.f('ix_assessment_instances_due_date'), 'assessment_instances', ['due_date'], unique=False)
    op.create_index(op.f('ix_assessment_instances_assigned_assessor_id'), 'assessment_instances', ['assigned_assessor_id'], unique=False)
    op.create_index(op.f('ix_assessment_instances_assessor_status'), 'assessment_instances', ['assigned_assessor_id', 'status'], unique=False)
    op.create_index(op.f('ix_assessment_instances_assessment_type'), 'assessment_instances', ['assessment_type'], unique=False)
    op.create_index(op.f('ix_assessment_instances_assessment_id'), 'assessment_instances', ['assessment_id'], unique=True)
    op.create_table('assessment_status_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('assessment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('from_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('to_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('changed_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('changed_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('approval_decision', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('approval_comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment_instances.id'], name=op.f('assessment_status_history_assessment_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.user_id'], name=op.f('assessment_status_history_changed_by_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('assessment_status_history_pkey'))
    )
    op.create_index(op.f('ix_assessment_status_history_to_status'), 'assessment_status_history', ['to_status'], unique=False)
    op.create_index(op.f('ix_assessment_status_history_changed_at'), 'assessment_status_history', ['changed_at'], unique=False)
    op.create_index(op.f('ix_assessment_status_history_assessment_timestamp'), 'assessment_status_history', ['assessment_id', 'changed_at'], unique=False)
    op.create_index(op.f('ix_assessment_status_history_assessment_id'), 'assessment_status_history', ['assessment_id'], unique=False)
    op.create_table('assessment_responses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('assessment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('control_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('compliance_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('maturity_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('effectiveness_rating', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('findings_en', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('findings_ar', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('gaps_identified_en', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('gaps_identified_ar', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('evidence_provided', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('evidence_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('evidence_quality', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('recommendation_en', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recommendation_ar', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('risk_rating', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('remediation_required', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('remediation_deadline', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('remediation_owner_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('control_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('control_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('assessed_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('assessed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('reviewer_comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assessed_by_id'], ['users.user_id'], name=op.f('assessment_responses_assessed_by_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment_instances.id'], name=op.f('assessment_responses_assessment_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['remediation_owner_id'], ['users.user_id'], name=op.f('assessment_responses_remediation_owner_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('assessment_responses_pkey')),
    sa.UniqueConstraint('assessment_id', 'control_id', name=op.f('uq_assessment_control'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_assessment_responses_control_id'), 'assessment_responses', ['control_id'], unique=False)
    op.create_index(op.f('ix_assessment_responses_assessment_status'), 'assessment_responses', ['assessment_id', 'compliance_status'], unique=False)
    op.create_index(op.f('ix_assessment_responses_assessment_id'), 'assessment_responses', ['assessment_id'], unique=False)
    # ### end Alembic commands ###
