from enum import Enum, IntEnum


class KnowledgeRank(IntEnum):
    ZERO = 0
    CANDIDATE = 1
    PLAUSIBLE = 2
    SUPPORTED = 3
    CORROBORATED = 4
    VERIFIED = 5
    ASSURED = 6


class KnowledgeStage(str, Enum):
    REALITY_CANDIDATE = "REALITY_CANDIDATE"
    TRACE_CANDIDATE = "TRACE_CANDIDATE"
    DEFINED_LOCUS = "DEFINED_LOCUS"
    DOMAIN_CONTRACT = "DOMAIN_CONTRACT"
    CLAIM_CANDIDATE = "CLAIM_CANDIDATE"
    RELATION_CANDIDATE = "RELATION_CANDIDATE"
    EVIDENCE_BINDING = "EVIDENCE_BINDING"
    RANK_ASSIGNMENT = "RANK_ASSIGNMENT"
    RESIDUAL_AUDIT = "RESIDUAL_AUDIT"
    JUDGMENT_CANDIDATE = "JUDGMENT_CANDIDATE"


class JudgmentStatus(str, Enum):
    CANDIDATE = "CANDIDATE"
    BLOCKED = "BLOCKED"
    DEFERRED = "DEFERRED"
    SUPPORTED = "SUPPORTED"
