# Generated by Django 6.0.3 on 2026-06-29 08:02

import django.db.models.deletion
import iam.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0149_soa_statement_of_applicability'),
        ('iam', '0024_soa_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementOfApplicability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('version', models.CharField(default='1.0', max_length=100, verbose_name='Version')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('approved', 'Approved')], default='draft', max_length=20, verbose_name='Status')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name='Approval date')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_soa', to=settings.AUTH_USER_MODEL, verbose_name='Approved by')),
                ('compliance_assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statement_of_applicability', to='core.complianceassessment', verbose_name='Compliance assessment')),
                ('folder', models.ForeignKey(default=iam.models.Folder.get_root_folder_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_folder', to='iam.folder')),
            ],
            options={
                'verbose_name': 'Statement of Applicability',
                'verbose_name_plural': 'Statements of Applicability',
            },
        ),
        migrations.CreateModel(
            name='SoAEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('applicability', models.CharField(choices=[('applicable', 'Applicable'), ('not_applicable', 'Not applicable')], default='applicable', max_length=20, verbose_name='Applicability')),
                ('justification', models.TextField(blank=True, verbose_name='Justification')),
                ('folder', models.ForeignKey(default=iam.models.Folder.get_root_folder_id, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_folder', to='iam.folder')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soa_entries', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('requirement_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soa_entries', to='core.requirementassessment', verbose_name='Requirement assessment')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.statementofapplicability', verbose_name='Statement')),
            ],
            options={
                'verbose_name': 'SoA Entry',
                'verbose_name_plural': 'SoA Entries',
                'ordering': ['requirement_assessment__requirement__order_id'],
                'unique_together': {('statement', 'requirement_assessment')},
            },
        ),
    ]
